nsacyber/HIRS

HIRS_Utils/src/main/java/hirs/data/persist/AbstractDigest.java
HIRS_Utils/src/main/java/hirs/data/persist/Digest.java
HIRS_Utils/src/test/java/hirs/data/persist/DigestTest.java

Zero-value hashes, and hashes of no data, are now
considered as matches to equal values instead of
treating them as 'unknown'.

[#10] Fix representation of zero-valued hashes

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java

This merge request adds Holder information for platform credentials.  This will display the common name and associated holder serial number.  If the holder serial number is linked to an existing endorsement certificate, a link will be provided.  Otherwise just display the serial number of the endorsement link.

[#6] Update Platform Credentials details page to display the Holder Information

---

HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/issued-certificates.jsp

This pull request adds the trashcan icon to the Attestation Certificates page of the portal.  
Fixes #17

[#17] Adding ability to delete Attestation Certificates on the ACA.

---

.travis.yml
settings.gradle
tpm_module/build.gradle

This MR improves the Travis CI build time by taking advantage of their Build Matrix feature. This allows us to parallelize building/testing the subprojects all at the same time. In particular, this optimization shaves off about 4-5 minutes total.
Doesn't close the issue #14 just yet, as we're waiting to hear on if we can pre-build a Docker image and host it on Docker Hub.

[#14] Parallelize Subproject CI Builds

---

HIRS_Utils/src/main/java/hirs/data/persist/certificate/EndorsementCredential.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/TPMSecurityAssertions.java
HIRS_Utils/src/test/java/hirs/data/persist/certificate/EndorsementCredentialTest.java

Update `EndorsementCredential` to correctly parse the `TPMSecurityAssertions` objects per the specification on pg.19 at www.trustedcomputinggroup.org/wp-content/uploads/Credential_Profile_EK_V2.0_R14_published.pdf
Closes #27

[#27] Fix TPMSecurityAssertions Parsing in EndorsementCredential

---

HIRS_Provisioner/src/main/java/hirs/provisioner/client/RestfulClientProvisioner.java

This change captures the log output from HIRS_Provisioner in the console like so:
```
TPM 1.2 detected.
--> Configuring provisioner
----> Deleting existing key store
----> Downloading truststore
--> Provisioning
----> Removing old provisioner scripts, if any
----> Provisioning TPM
----> Collecting device information
----> Got endorsement credential from TPM
----> Sending Attestation Identity Credential Request
----> Attestation Identity Provisioning succeeded
```
Closes #36

[#36] TPM Provisioner status output

---

HIRS_Utils/src/main/java/hirs/data/persist/IMAPolicy.java
HIRS_Utils/src/main/java/hirs/data/persist/ImaAcceptableRecordBaseline.java
HIRS_Utils/src/main/java/hirs/data/persist/ImaBaseline.java
HIRS_Utils/src/main/java/hirs/data/persist/ImaBlacklistBaseline.java
HIRS_Utils/src/main/java/hirs/data/persist/ImaIgnoreSetBaseline.java
HIRS_Utils/src/main/java/hirs/data/persist/QueryableRecordImaBaseline.java
HIRS_Utils/src/main/java/hirs/data/persist/SimpleImaBaseline.java
HIRS_Utils/src/main/java/hirs/ima/matching/BatchImaMatchStatus.java
HIRS_Utils/src/main/java/hirs/ima/matching/ImaAcceptableHashRecordMatcher.java
HIRS_Utils/src/main/java/hirs/ima/matching/ImaAcceptablePathAndHashRecordMatcher.java
HIRS_Utils/src/main/java/hirs/ima/matching/ImaRecordMatcher.java
HIRS_Utils/src/test/java/hirs/data/persist/BroadRepoImaBaselineTest.java
HIRS_Utils/src/test/java/hirs/data/persist/SimpleImaBaselineTest.java
HIRS_Utils/src/test/java/hirs/data/persist/TargetedRepoImaBaselineTest.java
HIRS_Utils/src/test/java/hirs/ima/matching/ImaAcceptableHashRecordMatcherTest.java
HIRS_Utils/src/test/java/hirs/ima/matching/ImaAcceptablePathAndHashRecordMatcherTest.java
HIRS_Utils/src/test/java/hirs/ima/matching/package-info.java

ImaAcceptableRecordBaseline and its subclasses have been updated to include
a containsHashes method to be able to match IMA measurement records
based solely on their hashes.  Supporting classes have been
updated or created as necessary.
Additionally, the set of path equivalencies as specified in the IMA
policy have been updated to include additional entries.
Closes #33.

[#33] IMA baselines can match measurements based solely on hashes

---

HIRS_ProvisionerTPM2/build.gradle
HIRS_ProvisionerTPM2/package/package.tpm2.centos7.sh
HIRS_ProvisionerTPM2/package/package.tpm2.ubuntu.sh

This merge request updates the Gradle Build and TPM 2.0 Provisioner packaging scripts to avoid deleting the `lib` folder in the target build directory. In doing so, this effectively "caches" the external dependencies and allows for CMake to detect and make use of the dependencies that were already downloaded.
Closes #47

[#47] Prevent deletion of external dependencies for TPM 2.0 Provisioner

---

HIRS_Utils/src/main/java/hirs/persist/DBPolicyManager.java
HIRS_Utils/src/test/java/hirs/persist/DBPolicyManagerTest.java

DBPolicyManager's getPolicy(appraiser, device) has historically
returned the default policy for an appraiser if none is defined
in the device group that the given device belongs to.  However,
this behavior does not in fact support the current use of devices,
groups, and policies; in the case where a group has no policy
assigned for a type of appraiser, the system is in a state
where that type of appraisal will not occur for devices in
a given group.  To better reflect desired behavior, the method
now returns null if a policy is not explicitly set for
the given (appraiser, device group) pair.
Closes #49.

[#49] Modify getPolicy behavior to reflect use

---

HIRS_Utils/src/main/java/hirs/data/persist/Alert.java
HIRS_Utils/src/test/java/hirs/data/persist/AlertTest.java

These changes simply add a field called 'displayTitle' to the Alert class to hold a human-readable title for each Alert instance.
Closes #55.

[#55] Add displayTitle to Alert

---

HIRS_Utils/src/main/java/hirs/data/persist/TPMBaseline.java
HIRS_Utils/src/main/java/hirs/tpm/TPMBaselineGenerator.java
HIRS_Utils/src/test/java/hirs/data/persist/TPMBaselineTest.java
HIRS_Utils/src/test/java/hirs/tpm/TPMBaselineGeneratorTest.java

TPM Baselines (whitelist and blacklist) that were created via csv file upload were observed to be consistently missing exactly one record.
The cause was the while() loop condition in TPMBaselineGenerator.parseBaseline().  The BufferedReader.ready() function that governed the loop only reports on the availability of the underlying stream for reading, not the content of that stream.  By calling reader.readLine() at the end of each iteration the loop would exit after reading the last line of a file but before processing and adding it to the baseline object.  Checking reader.readLine() directly to govern the while loop avoids this problem.
Closes #58

[#58] Modify while loop condition to read all lines

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
HIRS_AttestationCAPortal/src/main/webapp/common/common.js
HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/CertificateAuthorityCredential.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentIdentifier.java
HIRS_Utils/src/test/java/hirs/data/persist/certificate/PlatformCredentialTest.java

In addition to the added fields in #43, I have placed some additional spec defined 'behaviors' on new and present fields.  If a field is a 'must' and 'critical' but has no listed information 'NOT SPECIFIED' is displayed.  If it is 'should' or 'may', the field is hidden instead.
Also, some fields were combined.  Some where made into button panels and some of them have been defaulted to collapsed on certificate details page.
Closes #43

[#43] Additional certificate fields to display.

---

HIRS_Utils/src/main/java/hirs/data/persist/certificate/EndorsementCredential.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
HIRS_Utils/src/test/java/hirs/persist/DBCertificateManagerTest.java

Adds a selector method to retrieve ECs and PCs by their associated device
so they can be deleted.

Add selector for Endorsement Credential and Platform Credential Deletion

---

HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java

Adds null checks to prevent the issue described in the ticket.
Closes #69

[#69] Add null checks to Component Identifier Serial/Revision Trimming

---

HIRS_ProvisionerTPM2/src/Tpm2ToolsUtils.cpp
HIRS_ProvisionerTPM2/src/Utils.cpp

A couple of variables had conflicting names and the inner scope was
shadowing the outer. Style checker was complaining. Deleted one inner
definition and renamed another variable.

Fix Style Issue in Build

---

.ci/docker/Dockerfile.centos7
.ci/docker/Dockerfile.ubuntu18
HIRS_ProvisionerTPM2/CMakeLists.txt
HIRS_ProvisionerTPM2/docs/dependencies-centos.md
HIRS_ProvisionerTPM2/docs/developer-dependencies-centos.md
HIRS_ProvisionerTPM2/docs/developer-dependencies-debian.md
HIRS_ProvisionerTPM2/package/rpm-post-install.sh

There was a problem in the rpm-post-install.sh script
that ran as part of the CentOS7 rpm installation where
a link was being created called libcurl.so which pointed
to libcurl.so.4. If the link could not be created because
it already existed, the script would quit before finishing
and never place hirs-provisioner-tpm2 in a directory on
the PATH.
The proper solution was to link hirs-provisioner against
libcurl.so.4 so that it is clear which version of the API
was compiled against. This was not happening because
we were linking against a version of curl build by the CPR
project which was not properly embedding the SONAME in the
shared object file. By linking instead against the shared
object file distributed in the development package of
libcurl, hirs-provisioner-tpm2 now looks for …

[#78] hirs-provisioner-tpm2 on path after installation.

---

.travis.yml

Small MR to combine the package and system test phases into one phase on Travis. This reduces the runtime of build pipeline to about 14-16 minutes down from 20-30 minutes with the 3 phases.
Closes #87

[#87] Combine Packaging and System Tests into One Travis Test Phase

---

HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/policy.jsp
HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java

Updating code to list what specifically is unmatched for platform components on the validation page when there is a failure.
Updates include a small shift for the policy page, putting the correct order for setting them (top to bottom). Updated unit tests for the additional text that now appears on the tool tip for the validation failure icon.
Closes #96

[#96] Validation tooltip update

---

HIRS_ProvisionerTPM2/include/Logger.h
HIRS_ProvisionerTPM2/src/Logger.cpp

The main issue that was causing the error to appear was the fact that we statically create the Loggers for 5 of our classes in `HIRS_ProvisionerTPM2`. The way the `logging.properties` loading method was written in `Logger.cpp` it attempted to Log the new log level of the loggers.
The problem was that this all happens before we even get to the `main` method and initialize `Log4cplus` to begin with. Since Log4cplus wasn't initialized, when it attempted to update the log level for these `static` loggers and then Log what their new log levels were, it would throw the error.
This pull request just removes those unnecessary log statements and the problem is resolved.
Closes #95

[#95] Resolve Log4cplus Error complaining about no appenders

---

HIRS_Utils/src/main/java/hirs/persist/DeviceHealthManagerImpl.java
HIRS_Utils/src/main/java/hirs/persist/PersistenceConfiguration.java
HIRS_Utils/src/test/java/hirs/persist/DeviceHealthManagerImplTest.java

Super simple MR to remove the use of a magic string that originated in the HIRS_Utils PersistenceConfiguration class.
Closes #61

[#61] Remove Magic String Usage from PersistenceConfiguration

---

.ci/docker/Dockerfile.amazonlinux2
.travis.yml
HIRS_ProvisionerTPM2/package/package.tpm2.centos7.sh
package/scripts/common/db_create.sh
package/scripts/common/firewall_configure_tomcat.sh
package/scripts/common/get_amazon_linux_major_version.sh
package/scripts/common/ssl_configure.sh

Modified the build scripts to parse the Amazon Linux version as appropriate.  Default behavior is to treat version 2 the same as RHEL7.
Closes #90

Modify build scripts to enable installation on Amazon Linux

---

HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java

Small MR to add in a couple null checks to `Certificate` and `PlatformCredential`. I looked over `Certificate` and all of its subclasses pretty thoroughly and I only found a few places that needed an actual null check. Most of the other fields have to be there in order to form a valid Certificate, so it's more likely that either BouncyCastle or the Java Security API would throw a fit before we came across any issues.
With regards to testing, I know we don't have any certificates in violation of these new null checks, and, personally, I'm not sure where to get them. I would think PACCOR could create a new platform credential but I don't know that it has the ability to create one without making any extensions, and I'm not sure that I would request that as a feature. I'm also not certain …

[#18] Add in Null Checks for Certificate and Subclasses

---

HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp

Updated the System Platform Information section of the Platform and Endorsement details page.  Both pages had a field for Serial NR which was listed as optional in the code and wasn't being populated by any data.  The Platform page now checks for the type of certificate and displays either the platform or the chassis serial number and the Serial NR section was removed from the Endorsement as there was no equivalent serial number.
Close #115

[#115] Update System Platform Information for EK and Attribute Certs

---

.ci/system-tests/run-system-tests-tpm2.sh

docker-compose down is not cleaning up the hirs-aca-provisioner-tpm2 container for the TPM 2.0 system tests. Probably will need to add a "docker container prune" to the run-system-tests-tpm2 script.

[#122] Add clean up of dangling docker containers for TPM 2.0 system tests

---

HIRS_ProvisionerTPM2/config/doxygen.config
HIRS_ProvisionerTPM2/src/Properties.cpp

There were some warnings generated by Doxygen when compiling.
One was from an undocumented parameter for a method in the
Properties class. Many others were due to a setting that prevented
Doxygen from being able to associate function declarations with
their definitions if their parameters used standard library objects.
Closes #130.

[#130] Fixed Doxygen warnings.

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/service/SupplyChainValidationServiceImplTest.java
HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainValidation.java
HIRS_Utils/src/main/java/hirs/validation/CredentialValidator.java
HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java

This is generally how I plan to distinguish and check base and delta certs accordingly.
I decided to assign SupplyChainValidationServiceImpl.baseCredential in the policy.isPcValidationEnabled() loop to avoid looping through the set of PlatformCredential objects again just to find it.  baseCredential is then used to determine in the subsequent policy.isPcAttributeValidationEnabled() loop whether to validate a base or a delta credential, each with their respective methods in SupplyChainCredentialValidator.
Closes #108

[#108] Validity Check for Base and Delta Certs

---

HIRS_Utils/src/main/java/hirs/data/persist/ComponentInfo.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentIdentifier.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/V2/AttributeStatus.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/V2/ComponentIdentifierV2.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/V2/PlatformPropertyV2.java
HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
HIRS_Utils/src/test/java/hirs/data/persist/certificate/PlatformCredentialTest.java
HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java

The supply chain validation has reported non-matches for components that are initialized as null or blank or never initialized by code but by COTS. The end results is validation failure because the certificate compare will be null and the device report will list blank or Not Specified. This issue is to synch all to 'Not Specified'. Previous blank was set but that still caused issue with a blank compared to a 'Not Specified'.
Added additional information to be printed to the log when a failure occurs.
In addition, this issue may crop back up depending on what manufacturers do for empty slots on platforms.
Closes #103

Attribute Validation Match Update

---

HIRS_Utils/src/main/java/hirs/client/collector/DeviceInfoCollector.java

Threw in some calls to Trim the version tokens in the `collectTPMInfo` method. Issues were occurring with parsing C-Style strings into shorts on systems running the TPM2_Provisioner's `tpm_version` binary.
Closes #135

[#135] Fix DeviceInfoCollector's handling of C-Style Strings

---

HIRS_ProvisionerTPM2/src/tpm_version.cpp

The tpm_version tool can sometimes print a null
value as part of the TPM major version if the major
version is less than 4 characters. These nulls are
now removed before printing.

[#135] tpm_version prints output containing nulls.

---

.ci/docker/Dockerfile.tpm2provisioner
.ci/docker/docker-compose-tpm2.yml
.ci/system-tests/system_test_core.py

Code was recently added to update the platform attribute validation.
This ticket provides updates to support the validation:
1. Update the tpm2provisioner Docker image to use latest TPM2 Emulator. 
2. Update the docker-compose-tpm2.yml, so PACCOR can collect device info from within the container.
3. Enable platform attribute validation in **system_test_core.py:enable_supply_chain_validations()**, to be ran during system tests.

[#138] Add Platform Attribute Validation to System Tests (TPM 2.0 Emulator)

---

package/scripts/aca/certificate_generate.sh
package/scripts/common/db_create.sh

This is a small MR that does as advertised. We want to avoid port collisions when the ACA is run parallel with other webapps in a Tomcat deployment in Docker containers.
Closes #142

[#142] Make sure Tomcat stops completely in Docker containers before restarting it

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateRequestPageController.java

Updated the controller for the upload feature of the ACA for certificates and modified the platform certificate portion to restrict the upload if a base exists in that associated certificate chain associated with the same platform serial number.
Added code that deletes the entire chain if the base is deleted.
Closes #133 & #134

[#133] Multiple base restriction

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateRequestPageController.java

Modified the request class that handles uploading, deleting and other associated ACA actions, to only delete multiple associated certificates if the certificate being deleted is a base platform certificate.
Closes #154

[#154] Fix code for Delta Certificate Deletion

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateRequestPageController.java

This pull request fixes the issue of  multiple delta certificates not being uploaded because they are run through the same code that blocks base certificates.  A check was needed to fix the problem.
Closes #156

[#154] Fix multi delta certificate block

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/service/SupplyChainValidationServiceImplTest.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/validation-reports.jsp
HIRS_Utils/src/main/java/hirs/data/persist/AbstractEntity.java
HIRS_Utils/src/main/java/hirs/data/persist/AppraisalResult.java
HIRS_Utils/src/main/java/hirs/data/persist/NetworkInfo.java
HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainValidationSummary.java
HIRS_Utils/src/main/java/hirs/validation/CredentialValidator.java
HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java

This pull request contains 2 main changes, the first is transferring the status text from the attributes failure to the icon specifically for platform trust chain validation. Then this removes the third column on the validation page that singles out the icons for the attribute status. 
In addition, this status is also rolled up to the summary status icon and displays the text there as well for all that have failed.  This will modify the database.  The SupplyChainValidationSummary was updated to increase the message fields length to accommodate the underlying errors rolling up into this field.
Closes #166

[#166] Validation icon swap

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateRequestPageController.java
HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java

Through further testing with delta certificates that had differing begin validity dates, the code to test the sorting failed. This push includes a fix that places the deltas in the proper order.
In addition, this code includes a placeholder for deltas that don't have an existing holder certificate in the database.
Closes #181

[#181] Delta holder validation

---

HIRS_ProvisionerTPM2/include/CommandTpm2.h
HIRS_ProvisionerTPM2/src/CommandTpm2.cpp
HIRS_ProvisionerTPM2/src/ProvisionerTpm2.proto
HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp

The provisioner was updated to include methods to getQuote and getPcrlist by using the tpm2_tools commands.  The output from the commands are kept as strings and this is passed up to the ACA upon certificate request response.  The protobuf file was updated to reflect this and was changed to optional so that previous provisioner versions can still send to the ACA.
Closes #190

[#190] Provision update for quote and pcrs

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/rest/RestfulAttestationCertificateAuthority.java
HIRS_ProvisionerTPM2/src/ProvisionerTpm2.proto

This pull request closes the update to the restful interface of the ACA allowing for processing of a quote from the provisioner.  The protobuf was updated to reflect optional fields in the certificate request, this attribute allows older provisioner to still communicate with the ACA.  The protobut library crashes the communication if the proto file doesn't match.
Currently the ACA is just process and storing the values provided in variables at this stage.
Closes #191

[#191]  ACA Processing TPM Quote/PCRs from Certificate Request

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/CredentialManagementHelper.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateRequestPageController.java
HIRS_Utils/src/main/java/hirs/data/persist/AbstractEntity.java
HIRS_Utils/src/main/java/hirs/data/persist/ArchivableEntity.java
HIRS_Utils/src/main/java/hirs/data/persist/Device.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/DeviceAssociatedCertificate.java

This pull requests fixes an error produced when provisioning when the certificate from a previous provision is deleted from the ACA.  The error involves doing a look up for an existing certificate and getting nothing however this is due to not using the 'includeArchived' attribute for the Certificate Selector.  Include Archived is used when manually uploading a certificate.
In addition, some toString methods were added/updated to provide more information for future debug purposes.
Closes #202

[#202] Certificate fail to save upon deletion during provisioning FIXED

---

.ci/system-tests/system_test.py

1. Cleaned up python Imports.
2. Updated TPM 1.2 Provisioner docker image(on Docker Hub) to use https://github.com/nsacyber/HIRS/releases/download/v1.1.1/tpm_module-1.1.1-1574364941.0c2005.x86_64.rpm

Update TPM 1.2 Provisioner docker image with latest tpm_module (v1.1.1)

---

HIRS_Utils/src/main/java/hirs/utils/VersionHelper.java
HIRS_Utils/src/test/java/hirs/utils/VersionHelperTest.java

Revert previous changes to HIRS_Util classes related to VERSION file.  This resolves the FileNotFound errors encountered when running the latest HIRS_Provisioner.

Fix HIRS_Provisioner install error

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java

A corner case came up in which the serial number didn't contain a value.  This causes an ArrayOutOfBounds exception.  Added an additional check because the serial number isn't required.
Closes #234

[#234] Updated a check on the SERIAL_INDEX in certificate string map builder.

---

HIRS_ProvisionerTPM2/lib/CPR.CMakeLists.txt.in

This issue was resolved by modifying the CPR.CMakeLists.txt.in to no longer use the GIT_REPOSITORY and GIT_TAG.  Instead the URL and URL_HASH are used, pulling down the zip file.
I'm unsure as to what specifically causes this to work and not the repo pull but I am under the assumption that the zip contains everything that is needed whereas the repo and the git commands create the issue that it can't resolve when trying to pull the needed libraries.
Closes #254

[#254] Modified how TPM2 Provisioner pulls down sub module cpr

---

tools/tcg_rim_tool/src/main/java/hirs/swid/Main.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java
tools/tcg_rim_tool/src/test/resources/generated_no_cert.swidtag
tools/tcg_rim_tool/src/test/resources/generated_with_cert.swidtag

1. <File> under <Payload> for a rimel has name read from the attributes json file, while size and hash are calculated from the file given through `-l` command-line parameter.
2. `-v` will verify the <File> hash using what is given in the base RIM; `-v -l <filepath>` will verify the <File> hash using <filepath> instead.
Closes #275

[#275] Modify Payload filepath

---

build.gradle
tools/tcg_eventlog_tool/gradlew.bat

Added gradlew.bat which allow the tcg_eventlog_tool to be built on a windows 10 command shell.
To build on a windows command shell:
1. navigate to the tcg_eventlog_tool folder
2. run the gradle wrapper:
> gradlew.bat
To run the tcg_eventlog_tool from the a command shell:
1. navigate to the tcg_eventlog_tool folder
2. invoke using java -jar option to the tcg_eventlog_tool jar file with options:
> java -jar build\libs\tools\tcg_eventlog_tool-1.0.jar -h
another example:
> java -jar build\libs\tools\tcg_eventlog_tool-1.0.jar -f C:\Windows\Logs\MeasuredBoot\0000000059-0000000000.log -e 
closes #283

[#283] added a gradlew.bat for bulding the tcg_event_log on windows

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
HIRS_Utils/src/main/java/hirs/data/persist/ReferenceManifest.java

Updated Reference Manifest Page Controller so that the files being up loaded are properly handled.  Swid tag files that ended with 'new' were being saved as if they were tpm log files.  Updated how the code detects the type of file so that bin/rim/rimel are tested for and saved while anything else is processed as a swid tag.
Closes #290

[#290] RIM Upload modification

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/IssuedCertificatesPageControllerTest.java
HIRS_ProvisionerTPM2/include/CommandTpm2.h
HIRS_ProvisionerTPM2/src/CommandTpm2.cpp
HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp
HIRS_Utils/src/main/java/hirs/data/persist/PCRPolicy.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/IssuedAttestationCertificate.java

The initial problem involved an array out of bounds exception that occurred because the provisioner wasn't sending both sets of pcrs values (as previously coded).  This issue wasn't resolved.  Instead, since at some point the RIM file could have any signature size, the values that are sent from the provisioner are now modified to send the entire list instead of 2 specific sets.  
This caused the next issue in which that value was too large to store in the database.  Now the ACA takes the pcr list from the provisioner and stores that in a flat file.  
validation passes.
Closes #282

[#282] ACA Firmware Validation 500 External error resolution

---

tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagConstants.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java
tools/tcg_rim_tool/src/test/java/hirs/swid/TestSwidTagGateway.java
tools/tcg_rim_tool/src/test/resources/generated_no_cert.swidtag
tools/tcg_rim_tool/src/test/resources/generated_with_cert.swidtag
tools/tcg_rim_tool/src/test/resources/rim_fields.json

1. Firmware attribute QName objects were not spelled correctly
2. Move support RIM attributes under Payload element
Closes #295

[#295] Clean up base RIM attributes

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationService.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java
HIRS_ProvisionerTPM2/include/CommandTpm2.h
HIRS_ProvisionerTPM2/src/CommandTpm2.cpp
HIRS_ProvisionerTPM2/src/ProvisionerTpm2.proto
HIRS_ProvisionerTPM2/src/RestfulClientProvisioner.cpp
HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp
HIRS_Utils/src/main/java/hirs/data/persist/Device.java
HIRS_Utils/src/main/java/hirs/data/persist/PCRPolicy.java
HIRS_Utils/src/main/java/hirs/data/persist/SwidResource.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/IssuedAttestationCertificate.java
HIRS_Utils/src/main/java/hirs/data/persist/info/TPMInfo.java
HIRS_Utils/src/main/java/hirs/data/persist/tpm/PcrComposite.java
HIRS_Utils/src/main/java/hirs/data/persist/tpm/PcrInfoShort.java
HIRS_Utils/src/main/java/hirs/data/persist/tpm/PcrSelection.java

This code push adds the ability to validate the pcrs against the quote provided by the provisioner.  
This sequence happens after the first set of validations and to validate the quote a new summary has to be generated along with the previous validations.  
Code tested against valid and non-valid swidtag and rim files.
#236

[#236] TPM Quote validation update

---

HIRS_Utils/config/genXjcLibrary.sh

The current script for generating the xjc didn't check if the files already existed. This causes the script to run multiple times during a build, which slows down the build process. This tweak checks the location to see if it exists and skips generating the xjc again.

XJC Generation Tweak

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/reference-manifests.jsp
HIRS_AttestationCAPortal/src/main/webapp/common/common.js
HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageControllerTest.java
HIRS_Utils/src/main/java/hirs/data/persist/BaseReferenceManifest.java
HIRS_Utils/src/main/java/hirs/data/persist/BiosMeasurements.java
HIRS_Utils/src/main/java/hirs/data/persist/EventLogMeasurements.java
HIRS_Utils/src/main/java/hirs/data/persist/ReferenceManifest.java
HIRS_Utils/src/main/java/hirs/persist/DBReferenceManifestManager.java
HIRS_Utils/src/main/java/hirs/persist/ReferenceManifestManager.java
HIRS_Utils/src/main/java/hirs/persist/ReferenceManifestSelector.java
HIRS_Utils/src/main/java/hirs/tpm/eventlog/TCGEventLog.java
HIRS_Utils/src/main/java/hirs/tpm/eventlog/TpmPcrEvent.java
HIRS_Utils/src/main/java/hirs/tpm/eventlog/TpmPcrEvent1.java
HIRS_Utils/src/main/java/hirs/tpm/eventlog/TpmPcrEvent2.java

This commit includes a completed rewrite of the ReferenceManifestSelector framework.  Like the previous rewrite, it was easier and made more sense to create addition classes and that are specific to a type of RIM (base, support, measurement) for referencing in the DB.  Once this was rewritten the code was modified to validate the measurement against the support rim.
This PR is part 2 of #238

[#238] Client Upload rewrite and validation

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp
HIRS_Utils/src/main/java/hirs/data/persist/BaseReferenceManifest.java
HIRS_Utils/src/main/java/hirs/utils/ReferenceManifestValidator.java
HIRS_Utils/src/main/resources/identity_transform.xslt

This supersedes PR#300 
Changes:
- Add frontend elements to display validation results for support RIM hash and baseRIM signature
- Created new class in hirs.utils to handle validation actions
- Details page controller calls validator class and pushes results to frontend
An example of a successfully validated support RIM and signature:
https://10.112.29.32:8443/HIRS_AttestationCAPortal/portal/rim-details?id=1052044a-d5e7-4898-abb5-f7cc8bbb241a
<br><br>
Closes #298

[#298] Add validation for support RIM hash and base RIM signature.

---

tools/tcg_rim_tool/tcg_rim_tool.spec

The packaging script for tcg_rim_tool was failing to find the jar file for copying.

Fix path for jar file

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp

If the Support RIM was uploaded, separately, first, then the Base; the base RIM details page would display a linked Support RIM but no expected PCR values.
To replicate this behavior on master, upload a support rim.  Then separately upload a Base RIM.

Bug Fix for Base RIM Details Page

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java

Updated the file to just use the fileName from the ReferenceManifest for the downloaded name.
Closes #324

[#324]  Update filenames when downloading (RIM)

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/IssuedCertificateAttributeHelper.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/AbstractAttestationCertificateAuthorityTest.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/IssuedCertificateAttributeHelperTest.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/service/SupplyChainValidationServiceImplTest.java

These are unit tests that were not run on the merge request #327 for issue 308.  The unit tests uses certificate (EC and 2 CAs) that don't match for SKI to AKI or issuer string fields.  The O= field isn't required and the code in #327 was changed to use SKI first then a sorted RDN list.  See #327.  A note was left in the unit tests that the test certs need to be updated.
Another set of unit tests were updated because the passed in null parameter for a set<objects> was throwing NPEs.

[#308] Updated unit tests

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp

Updated the printing of the event number for the failed events.  This is to match them with the event number on the support rim page.  Support rim page starts at 1 but the method used on the failure page starts at 0.  Also while investigating this issue, I noted that the coloring of the failure event disappears after the first viewing of that page.  This was fixed.  The conditions to check for an error were being ignored after the first load.

Firmware Event Numbering Fix

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java

This is a change to the details page handler for the RIM files.  The rimel files that are uploaded by themselves are not updated with manufacturer or model information, and the controllers are referencing that information when looking up database information.  This causes a null exception and a funky output on the screen.  This commit fixes this issue.

RIMEL Upload bug fix

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java
scripts/download_validation_reports.sh

This pull request creates a command line script to invoke the download function on the validation report page on the ACA Portal.  Execution is summarized as:
1. get user parameters for filter start and end times in the format yyyy-mm-dd
2. pull data from the validation-reports/list end point
3. parse data for create time of each report and corresponding device name
4. pass user parameters, create times, and device names to validation-reports/download endpoint
5. CSV output is printed to standard output
Closes #336

[#336] Script to download ACAPortal validation reports

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java

This is a quick fix for a null pointer exception that is occurring because the parsed values from the device's pcr list is not populated.  They did have something but they didn't match what is in the RIM (algorithm).  Therefore, there should be a failure.

Windows PCR list Failure fix

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java

Updated the code for authority serial number and serial number for the general info for any certificate to no longer use the getLong method of the Big Integer object.  This truncated the value.  Instead, the new code uses the Hex.toHexString method from bouncy castle.

Serial Number Display Fix

---

HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java

Updated the code with additional OIDs for the algorithms that certificates use for the signatures.  And updated the isIssuer method to not use the hard coded algorithm string.

Certificate Signature OID Update

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/service/SupplyChainValidationServiceImplTest.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp
HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp
HIRS_Utils/src/main/java/hirs/data/persist/BaseReferenceManifest.java
HIRS_Utils/src/main/java/hirs/data/persist/ReferenceDigestValue.java
HIRS_Utils/src/main/java/hirs/data/persist/ReferenceManifest.java
HIRS_Utils/src/main/java/hirs/data/persist/SupportReferenceManifest.java
HIRS_Utils/src/main/java/hirs/data/persist/SwidResource.java
HIRS_Utils/src/main/java/hirs/persist/DBReferenceDigestManager.java
HIRS_Utils/src/main/java/hirs/persist/DBReferenceEventManager.java
HIRS_Utils/src/main/java/hirs/persist/ReferenceDigestManager.java
HIRS_Utils/src/main/java/hirs/persist/ReferenceManifestSelector.java
config/checkstyle/sun_checks.xml

In an effort to keep the PR a bit smaller.  This is the first part of event digest validation that is associated with #343.  
The first main thing this PR addresses is updating the UI to display the differences in support RIMs whether they are Supplemental or Patch. 
Because of updating the UI, more had to be updated in the background to make sure the support rims were updated with the correct information from the associated base, which depends on when each are uploaded and how they associate with one another.  A lot of the code change have to do with moving code around so that different fields within the RIM objects could be updated.
Also fixed a visual error that causes all support RIM events to show up red (error).  This had to do with the comparing of events by event number, which …

[#343] Event digest update (UI)

---

tools/tcg_rim_tool/src/main/java/hirs/swid/utils/HashSwid.java
tools/tcg_rim_tool/src/test/resources/generated_no_cert.swidtag
tools/tcg_rim_tool/src/test/resources/generated_with_cert.swidtag

Encode the calculated Payload file hash in base64 before writing out to the base RIM.
Closes #359

[#359] Check base64 encoding for base RIM attributes

---

.travis.yml
HIRS_ProvisionerTPM2/src/CommandTpm2.cpp

TRavis ci Builds are failing due to the new restriction on Docker Hub for anonymous pulls. This PR addresses this issue.
closes issue-367

Docker Pull update for Travis ci

---

HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentClass.java
HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/V2/ComponentIdentifierV2.java
HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
HIRS_Utils/src/main/resources/component-class.json
HIRS_Utils/src/test/java/hirs/data/persist/certificate/attributes/ComponentClassTest.java
HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java
HIRS_Utils/src/test/resources/config/component-class.json

These changes update the component class object to handled SMBIOS registry components IDs along with the TCG ones presented originally.  The unit tests also were updated to use the new structure of the class and added additional tests for the SMBIOS entries.
The current sub-entries for the SMBIOS registry are just place holders.

SMBIOS registry update for Component Identifiers

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateRequestPageController.java
tools/tcg_rim_tool/src/main/java/hirs/swid/CredentialParser.java

Added an additional catch statement to the parsing of certificates that are PEM in case of a DecoderException for Base64.decode method.  Instead of going to a blank page with the error, the ACA catches the exception and states on the page in which the file was uploaded to.

Base64 decode exception

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java

SupplyChainValidationServiceImpl class now checks the keystore for all intermediate and root CAs chained to a given signing cert.  Errors encountered during the check are reported to the ACA.
Closes #345

[#345] Add cert path validation to ACA

---

HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java

One line change to SupplyChainCredentialValidator to loop fully through truststore.  Removing the while loop condition will prevent it from exiting prematurely.
Closes #345

[#345] Modify SupplyChainCredentialValidator class to loop through truststore

---

HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java

Previous changes to this method did not adequately refactor the old recursive code.  This PR accounts for all possible sequences of trusted certs encountered in the truststore so that the full issuing chain is discovered if present.
Closes #345

[#345] Refactor recursion in SupplyChainCredentialValidator.validateCertChain

---

package/rpm/HIRS.spec
tools/tcg_eventlog_tool/build.gradle

Add checks to avoid conflict during ACA and tcg_eventool install over vendor-tables.json.
Closes #382

[#382] Install check to avoid file conflict

---

HIRS_Utils/src/test/java/hirs/tpm/eventlog/events/TCGEventLogEventsTest.java

Missed an update for a method that was updated with a new exception thrown.

Checkstyle fix on a Unit Test

---

HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java
HIRS_Utils/src/test/resources/hirs/validation/sample_paccor_output.txt

Updated unit tested to correct the failures that were occurring because of the updated code changes.

Delta Component Unit Tests Fixes

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AcaDbInit.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/model/PolicyPageModel.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/Page.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PolicyPageController.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/index.jsp
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/issued-certificates.jsp
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/policy.jsp
HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainPolicy.java

This is an initial commit updates the policy page.  Adds additional policies for generating a DevID.  The underlying code doesn't actually generate one yet.  But the SupplyChainPolicy holds the flags.
```
- Generate DevID Certificate: Disabled 
-- DevID Certificate Validity period: Disabled 
-- DevID Certificate Renewal period: Disabled
```
This mimics the normal attestation setup.

[#396] DevID display update

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_Utils/src/main/java/hirs/utils/JsonUtils.java

The rim hash validation icon is coming up red when both base and support RIMs are loaded.  This fixes that issue.
The file name of the associated resource file (support RIM) in the swidTag did not match the actual file name of the support rim.  This causes the if condition that leads to the support rim hash check to fail.  The if condition has now been changed to ignore case since a small port of the file name was different.

Support RIM Filename Fix

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp
HIRS_Utils/src/main/java/hirs/data/persist/BaseReferenceManifest.java

The rimlinkhash meta information wasn't linking up with the associated swidtag.  This is because the wrong hash look up was being used.  Previously when the hexDecHash and base64Hash were implemented, the main focus was on the rimel and not the swidtag.

RimLinkHash Fix

---

package/rpm/HIRS.spec
tools/tcg_eventlog_tool/README.md
tools/tcg_eventlog_tool/build.gradle
tools/tcg_eventlog_tool/scripts/vendor-table.sh

This commit updates the location of the vendor-table.json which is used by the ACA and the eventlog tool.  The previous change moved the vendor-table.json to a separate folder, however the code was not updated to reflect the change.  This instead updates how the two install handle the file.  The ACA was updated not to clobber the file if it exists and the eventlog tool was updated to do the same through an additional script during post install.
This was tested by installing the ACA first, then the eventlog tool.  And then tested in reverse, both attempts passed without crashing.

Vendor Table JSON refactor

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/PciIds.java
HIRS_ProvisionerTPM2/include/Utils.h
HIRS_ProvisionerTPM2/src/ProvisionerTpm2.proto
HIRS_ProvisionerTPM2/src/RestfulClientProvisioner.cpp
HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp
HIRS_ProvisionerTPM2/src/Utils.cpp
HIRS_Utils/build.gradle
HIRS_Utils/src/main/java/hirs/data/persist/PCRPolicy.java
HIRS_Utils/src/main/java/hirs/tpm/TPMBaselineGenerator.java
HIRS_Utils/src/main/java/hirs/utils/PciIds.java
HIRS_Utils/src/main/java/hirs/utils/ReferenceManifestValidator.java
HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java

- Modify ACA RIM validation to search for a signing cert if the base RIM does not have an embedded cert.
- Validate the ca chain of the found signing cert.
The changes to the RIM controller and SupplyChainValidationServiceImpl are summarized by the following:
1. Parse from the RIM the embedded cert if it is present, or the subject key identifier (skid).
2. Loop through all certs found and compare to the embedded cert or skid for a match.
3. If a match is found, validate the Signature element of the RIM.
4. If the Signature element is valid, get the signing cert's respective CA chain and attempt to validate.
Closes #381

[#381] Update RIM validation in ACA

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp

The provisioner was throwing an error to the standard printout because of protobuf. This had to do with the recent change to checking the Identity Claim Response and the use of the has_credentialBlob check.

Protobuf Credential Blob check fix

---

tools/tcg_rim_tool/src/main/java/hirs/swid/Main.java
tools/tcg_rim_tool/src/main/java/hirs/swid/utils/Commander.java

These changes require the user to give signing credentials via -k and -p, or indicate default credentials via -d.  If neither case is true then the tool exits with an error message.
Closes #423

[#423] Default signing credentials option for tcg_rim_tool

---

tools/tcg_rim_tool/build.gradle
tools/tcg_rim_tool/package.sh
tools/tcg_rim_tool/tcg_rim_tool.spec

Changes: 
- Add git timestamp and hash to the rpm name.
- Centralize version number to package.sh.
Closes #437

[#437] Add versioning to tcg_rim_tool RPM name

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp

This issue didn't actually involve the Device object not updating the validation status.  This is a missed changed for #442 .   The Certificate Response object check caused a problem with reading the response and ignored the status.
Closes #458

[#458] Validation Status fix

---

HIRS_Provisioner.NET/hirs/Resources/ProvisionerTpm2.proto
HIRS_Provisioner.NET/hirs/appsettings.json
HIRS_Provisioner.NET/hirs/src/Program.cs
HIRS_Provisioner.NET/hirs/src/client/Client.cs
HIRS_Provisioner.NET/hirs/src/client/IHirsAcaClient.cs
HIRS_Provisioner.NET/hirs/src/config/CLI.cs
HIRS_Provisioner.NET/hirs/src/config/ClientExitCodes.cs
HIRS_Provisioner.NET/hirs/src/config/Settings.cs
HIRS_Provisioner.NET/hirs/src/deviceInfo/ClassicDeviceInfoCollector.cs
HIRS_Provisioner.NET/hirs/src/deviceInfo/IHirsDeviceInfoCollector.cs
HIRS_Provisioner.NET/hirs/src/provisioner/IHirsProvisioner.cs
HIRS_Provisioner.NET/hirs/src/provisioner/Provisioner.cs
HIRS_Provisioner.NET/hirs/src/tpm/CommandTpm.cs
HIRS_Provisioner.NET/hirsTest/hirsTest.csproj
HIRS_Provisioner.NET/hirsTest/src/client/ClientTests.cs
HIRS_Provisioner.NET/hirsTest/src/config/SettingsTests.cs
HIRS_Provisioner.NET/hirsTest/src/provisioner/ProvisionerTests.cs

Also hides the error that is written to console when the TSS library can't find the resource management daemon.

.NET provisioner update usage of static paccor file 

---

HIRS_Utils/src/main/java/hirs/tpm/eventlog/TpmPcrEvent.java
HIRS_Utils/src/main/java/hirs/tpm/eventlog/TpmPcrEvent1.java
HIRS_Utils/src/main/java/hirs/tpm/eventlog/TpmPcrEvent2.java
HIRS_Utils/src/main/java/hirs/tpm/eventlog/events/EvConstants.java
tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Commander.java

Adds support for SHA384 and SHA512 for TPM event logs. 
closes #485

[#485] Event log spdm prep

---

.github/workflows/build_aca_image.yml

A small typo error in the build_aca_image.yml

[#490] Fixing a typo in the build Docker image workflow

---

tools/tcg_rim_tool/src/main/java/hirs/swid/Main.java
tools/tcg_rim_tool/src/main/java/hirs/swid/utils/CredentialArgumentValidator.java

These changes properly validate the credential argument(s) given by the user for both signing and validating cases.
Closes #520

[#520] Fixed credential input validation

---

HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentClass.java

Do to hash conversions, the alphanumeric format of the component type comes out lowercase, modified equals clause to ignore case.

Updated ComponentClass TypeId equals

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java

The 500 error indicated in issue [#502] looks like it stems from the default Zone causing an error when getting the end time for 'Now'.
Added a specific zone id.

[#502] Validation report download 500 error

---

build.gradle

Converts command in `build.gradle` to use `ByteArrayOutputStream` in order for it the git command to work properly in Eclipse.
Fixes issue #531.

Fix to build.gradle on Eclipse

---

.github/workflows/hirs_unit_tests.yml
.github/workflows/package_centos.yml
.github/workflows/system_test.yml

Any code intended for the master branch should use a branch name with a lower case "v2" in the name.
The "main" branch will be used as the target branch for the migration effort and not currently trigger these actions.
Any code intended for the main branch should use a branch name with a lower case "v3" in the name.
This would effect the following actions:
* HIRS Build and Unit Test
* HIRS packages for centos
* HIRS System Tests
closes: 536

[#536] Create filter for Github actions to trigger

---

HIRS_AttestationCAPortal/build.gradle
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/HIRSApplication.java
HIRS_AttestationCAPortal/src/main/resources/application.properties
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/tags/page.tag

```./gradlew bootRun``` will build the ACA and launch it with an embedded tomcat 
<br/>
```./gradlew bootWar``` will generate an executable war file. This war can be executed on any system with Java 17, including on Windows or Mac.
<br/>
When using either of these options,<br/>
* Once fully launched, the portal is accessible at localhost:8080.
* TLS is not available yet.
* The database must be set up prior to attempting to launch the ACA. The db_create.sh script under package/scripts/db can be used to set up an installed mariadb on Linux. On other systems, or if direct set up of the database is desired, the last 3 lines of that script contain mysql statements. Those 3 statements are all that are needed to get the db ready.
closes #538

bootRun and bootWar 

---

tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagConstants.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagValidator.java
tools/tcg_rim_tool/src/test/java/hirs/swid/TestSwidTagGateway.java
tools/tcg_rim_tool/src/test/resources/generated_default_cert.swidtag
tools/tcg_rim_tool/src/test/resources/generated_timestamp_rfc3339.swidtag
tools/tcg_rim_tool/src/test/resources/generated_timestamp_rfc3852.swidtag
tools/tcg_rim_tool/src/test/resources/generated_truststore_embed.swidtag
tools/tcg_rim_tool/src/test/resources/generated_user_cert.swidtag
tools/tcg_rim_tool/src/test/resources/generated_user_cert_embed.swidtag

The unit tests were failing to validate because `<SoftwareIdentity id=...` and `<Timestamp>` must be in unique namespaces from the SWID schema.  In order to pass validation these changes add the following custom namespaces:
- `<SoftwareIdentity pcRim:id=...`
- `<rfc####:timestamp .....>`
Unit tests have been updated accordingly.
Closes #501

[#501] Add namespaces to resolve failing schema validation

---

HIRS_AttestationCAPortal/build.gradle

These commands should work as expected:
```./gradlew buildRpm```: Creates plain war: HIRS_AttestationCAPortal/build/libs/HIRS_AttestationCAPortal.war and an rpm: HIRS_AttestationCAPortal/build/distributions/HIRS_AttestationCAPortal*.rpm
```./gradlew bootRun```: Launches the ACA in an embedded tomcat.
```./gradlew bootWar```: Creates a bootable war: HIRS_AttestationCAPortal/build/libs/HIRS_AttestationCAPortal.war
The name of the war file matters when given to tomcat. If it includes any other characters, the portal url will include those extra characters.
This command will cause issues with gradle:
```./gradlew bootWar buildRpm```

Supporting buildRpm alongside bootRun/bootWar

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceDigestValueRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceManifestRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/EventLogMeasurements.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/ReferenceDigestValue.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java

This PR fixes issues with displaying associated measurement events for the Reference Manifest support file.  If the support file is deleted, it now removes all associated events.  Also the repository calls are updated and the main referencing will be done by file hash instead of UUID.
This PR fixes issues associated with item 7 in #534

Reference Digest value UI Update

---

tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java
tools/tcg_rim_tool/src/test/resources/generated_timestamp_rfc2315.swidtag

Assign a value to the timestamp object to avoid the NPE thrown.  Update the test pattern file to incorporate latest updates.
Closes #566

[#566] Fix failing testCreateTimestampRfc2315

---

HIRS_AttestationCA/build.gradle

Spring boot allows us to build v3 on any system that supports Java. Calling genJavaProtoBuf.sh introduces a dependency on bash. We'd need to support a powershell script to avoid problems building on Windows.
I found google produces a protobuf gradle plugin that looks portable to other systems. https://github.com/google/protobuf-gradle-plugin The CI tests seem to pass, and I've tested successfully on Linux and Windows. Using the plugin should also remove a requirement to install the protobuf compiler prior to building.
I was not able to test effects on different IDEs. Posting this as a PR to see if the team finds any issues with using this plugin.

Use protobuf-gradle-plugin to replace a system dependency

---

.ci/docker/Dockerfile.ubuntu22ci
HIRS_AttestationCAPortal/build.gradle
package/scripts/aca/aca_check_setup.sh
package/scripts/aca/aca_remove_setup.sh
package/scripts/aca/aca_setup.sh
package/scripts/db/db_create.sh
package/scripts/db/db_drop.sh
package/scripts/db/mysql_util.sh
package/scripts/pki/pki_chain_gen.sh
package/scripts/pki/pki_setup.sh
test.sh

Adds a docker file for ubuntu 22 and makes adjustments to ACA setup scripts for Ubuntu.
To build an install file:
./gradlew bootWar
./gradlew buildDeb
package will be written to HISRS_AttestationCAPortal/build/distributions/
for Ubuntu the package name needed to be lower case with a dash in the first part of the name. 
Package name will be: hirs-attestationca_ver.date.commit.el8-1_amd64.deb
To install deb file use dpkg -i. Example
dpkg -i HIRS_AttestationCAPortal/build/distributions/hirs-attestationca_2.1.3.1697051798.d968080a.el8-1_amd64.deb
Note: to run setup scripts use bash vs sh on an Ubuntu terminal:
bash package/scripts/aca/aca_check_setup.sh
closes: #598

Add Ubuntu support for V3

---

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java

I tested manually uploading a series of certificates to test the list pages functionality when it comes to sorting and other visual aspects of the data table.  I encountered a certificate that caused the ACA to throw a 500 error.  This was due to an IllegalStateException while parsing a certificate that contained an 'unexpected object'.  Since this is a bouncy castle error, it is hard to parse out what the object actually is that is causing the error to be thrown.  For now, the parsing method in the certificate page controller is being updated to catch the exception, at least, so that the ACA doesn't crash. The platform in question is a Dell Power Edge R640 base SCV.
The Error: `java.lang.IllegalStateException: unexpected object: org.bouncycastle.asn1.ASN1Integer`

Uploading Platform Credential IllegalStateException Fix

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/ArchivableEntity.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CACredentialRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CertificateRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/EndorsementCredentialRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/IssuedCertificateRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/PlatformCertificateRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceManifestRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java

This pull request has some bug fixes and migrated functionality that was not included in the original push.  Due to unit test migration, there was a problem found with a unit test that calls the archive method for DB entities.  This function wasn't originally set up to work.  This PR includes the call and fixes up issues with the /list portion of the ACA portal displaying the correct number of items displayed and not the number in the DB.
In addition, while testing there was a mistake that led to a 500 error that wasn't covered in the try/catch handling.  When uploading a rim to a certificate page and vice versa; these actions produced 500 errors for IllegalStateException and Nullpointer.   The nullpointer can't be handled by our code because it is in the parsing libraries that are …

V3 server UI fixes

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CertificateRepository.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/RimDatabasePageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java

The usage of getReferenceById returns an object regardless if the uuid is valid.  This causes an issue when a false uuid is used and then produces a EntityNotFoundException when trying to access an attribute of the object returned.  These changes address either not using that specific call and changing to one that will return null if the uuid is invalid.  But also using the exists function of the repository to verify an invalid uuid.

DB Returning non-null but blank Objects

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/ArchivableEntity.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceManifestRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/SupplyChainValidation.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/info/ComponentInfo.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/AbstractProcessor.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/helper/CredentialManagementHelper.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/ValidationService.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/SupplyChainCredentialValidator.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java

After being able to provision and environment that has all of the artifacts that the ACA needs to complete a provision with all policy validations enabled, various issues were found and cleaned up.  This PR now allows for a completion.  However the last test does fail because of mismatched components and signature invalid on the tested BaseRIM.  As these are not initially seen as ACA bugs, I'm pushing this up for further testing.
In addition this updates some visual elements that weren't able to be tested.  1) the icon for firmware on the validation page was not linking to anything.  2) componentInfo isComplete was being handled in the reverse manner 3) the paccor output string was never being used for component comparison because it is never saved to the db and would be cleared on the …

ACA Provisioning Clean up

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/Appraiser.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/AppraiserTest.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/TestAppraiser.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/tpm/TPM2ProvisionerStateTest.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/tpm/TestTPM2ProvisionerState.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/CertificateTest.java

[Issue 615](https://github.com/nsacyber/HIRS/issues/615) includes:
Migration into the main branch's `HIRS_AttestationCA/src/test`, including the following 3 unit tests from master:
- `HIRS_Utils/src/test/java/hirs/persist/TestTPM2ProvisionerState`
- `HIRS_Utils/src/test/java/hirs/appraiser/AppraiserTest`
- `HIRS_Utils/src/test/java/hirs/appraiser/TestAppraiser`
- Fixing of `HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/CertificateTest` in main branch to replace some deprecated methods with up-to-date ones. Runs the same as before, but without a warning in the console.

HIRS_Utils Unit Tests Migration from /hirs/persist/ and /hirs/appraiser/ directories

---

HIRS_AttestationCA/config/spotbugs/spotbugs-exclude.xml
HIRS_AttestationCAPortal/config/spotbugs/spotbugs-exclude.xml
HIRS_Structs/config/spotbugs/spotbugs-exclude.xml
HIRS_Utils/config/spotbugs/spotbugs-exclude.xml
build.gradle
tools/tcg_eventlog_tool/config/spotbugs/spotbugs-exclude.xml
tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Commander.java
tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
tools/tcg_rim_tool/config/spotbugs/spotbugs-exclude.xml

This is the first step for adding spotbugs (formerly findbugs) back into the build.  The configuration is in place but the majority of the projects are being excluded.  The eventlog (a small sample size) is however being run with the proper corrections committed.
This is the first part of #642 
To initial the "spotted" bugs you have to take out the line in the exclude file, the entire match tag.
`<Match>`
`        <Package name="~hirs\.structs.*" />  `
`   </Match>`
as an example for HIRS_Structs

[#642] Initial Spotbugs Setup

---

HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
tools/tcg_rim_tool/src/main/java/hirs/swid/Main.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java
tools/tcg_rim_tool/src/test/java/hirs/swid/TestSwidTagGateway.java
tools/tcg_rim_tool/src/test/resources/generated_default_cert.swidtag
tools/tcg_rim_tool/src/test/resources/generated_timestamp_rfc3339.swidtag
tools/tcg_rim_tool/src/test/resources/generated_timestamp_rfc3852.swidtag
tools/tcg_rim_tool/src/test/resources/generated_user_cert.swidtag
tools/tcg_rim_tool/src/test/resources/generated_user_cert_embed.swidtag

These changes address some errors that were thrown during validation of valid RIMs.  
`Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.trustStore" is null`
The truststore List object is now set where it previously was not for validating flat files.  The hash calculation for support RIMs was also modified for consistency with the rimtool.
`Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "subjectKeyIdentifier" is null`
All base RIM signatures now include KeyName, which is used as the skid for validation.  Unit test files have been updated accordingly.
Closes #646

[#646] Fix broken rimtool validation

---

.github/workflows/hirs_unit_tests.yml

updated github action to copy artifacts for subprojects that now have unit tests
This was tested in a fork with results here: 
https://github.com/iadgovuser58/HIRS/actions/runs/7559337978

[#674] Updated github actions for unit test artifacts

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/EndorsementCredential.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/CommonCriteriaMeasures.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentAddress.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentIdentifier.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/FIPSLevel.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/PlatformProperty.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/TBBSecurityAssertion.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/URIReference.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/V2/ComponentIdentifierV2.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/V2/PlatformPropertyV2.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/PciIds.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/CertificateAttributeScvValidator.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/PlatformCredentialTest.java
HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/CertificateDetailsPageControllerTest.java

This is a tear from #652 that doesn't include the updated BC version update.  This gets rid of the deprecated instance with the various DERUTF8String issue.
This gets rid of a stack overflow issue that I have but not the one that occurs when getting rid of the ASN1ApplicationSpecific class.

BouncyCastle Prerequisite changes

---

HIRS_Utils/src/main/java/hirs/utils/VersionHelper.java
HIRS_Utils/src/test/java/hirs/utils/VersionHelperTest.java

The version number was not showing up on the ACA Portal.  This was due to the changes in how the ACA was packaged and loaded when switching from v2 to v3.  The location has been updated in #671, this PR updates the code to use the new location.

Verison helper update

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Device.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/info/NetworkInfo.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/report/DeviceInfoReport.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/DeviceTest.java

Code checked in from the last spotbugs PR push caused issues with the DeviceTest unit test.  The issue revolved around the equals and hashCode methods that were initially be done by lombok.  Auto generated by an IDE also failed (using Objects).  The issue came up because the methods all called super.equals().  I took this out and all issues were resolved. Lastly the null timestamp unit test was changed because the value will never be null.

Unit Test failures as of 1/22

---

tools/tcg_rim_tool/src/main/java/hirs/swid/Main.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagConstants.java
tools/tcg_rim_tool/src/main/java/hirs/swid/utils/Commander.java

These changes support `rim -V` or `rim --version`, which will print the following message to console:
`TCG rimtool version: [version]`
Closes #660

[#660] Add -V|--version for easy access to rimtool version number

---

HIRS_Structs/build.gradle
HIRS_Structs/src/test/java/hirs/structs/converters/SimpleStructBuilderTest.java
HIRS_Structs/src/test/java/hirs/structs/converters/SimpleStructConverterTest.java

[Issue 685](https://github.com/nsacyber/HIRS/issues/685) includes:
Modification of the following unit tests from the main branch's  `HIRS_Structs` subproject, in which all TestNG properties were replaced with JUnit5:
- `HIRS_Structs/src/test/java/hirs/structs/converters/SimpleStructBuilderTest.java`
- `HIRS_Structs/src/test/java/hirs/structs/converters/SimpleStructConverterTest.java`
- `HIRS_Structs/build.gradle`

Migration Fixes: HIRS_Structs Unit Tests

---

.gitignore

Additions to the .gitignore file for the .NET code weren't copied over with #662 #663.

Git ignore updates for the .NET provisioner

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/EndorsementCredential.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/CommonCriteriaMeasures.java
HIRS_Utils/src/test/java/hirs/utils/BouncyCastleUtilsTest.java
settings.gradle

Bouncy Castle, updating the version from 1.70 (2021) to 1.77 (2023)
While expecting a StackOverFlow error from uploading an EK certificate,
this is not occurring.  A unit test had to be updated because the
previous BouncyCastle X500Compare.equals() method returned false for 2
empty string compares.  Now it returns true.

Bouncy Castle version update

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/PciIds.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/provision/helper/IssuedCertificateAttributeHelperTest.java

ASN1UTF8String change to DERUTF8String so that the vendor string aren't throwing exceptions because ANS1UTF8String.getInstance does not take Strings
If the file is present, the current set of bouncycastle utilized code tries to create an ANS1UTF8String object from the vendor translations but ASN1UTF8String is abstract and the getInstance does not take in String.

PCI Ids Translation Fix

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CACredentialRepository.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java

Updated the code to properly check for database values that are archived vs not archived.
Closes #684

[#684] Green Check mark fix

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/CertificateAttributeScvValidator.java
HIRS_Utils/src/main/java/hirs/utils/BouncyCastleUtils.java
HIRS_Utils/src/main/java/hirs/utils/VersionHelper.java
HIRS_Utils/src/main/java/hirs/utils/digest/OptionalDigest.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TCGEventLog.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TpmPcrEvent.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TpmPcrEvent1.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TpmPcrEvent2.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiGptPartition.java

This commit is for the 3rd listed issue on #705.  The green check mark test was causing an error from ASN1UTF8String.getInstance.  And did some checkstyle fixes.
To replicate, you should just need to select PC attribute policy and provision.  My test was done on a dell.

[#705] PC Attributes Provision Error

---

HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
tools/tcg_rim_tool/src/main/java/hirs/swid/CredentialParser.java
tools/tcg_rim_tool/src/main/java/hirs/swid/Main.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java
tools/tcg_rim_tool/src/main/java/hirs/swid/utils/Commander.java
tools/tcg_rim_tool/src/main/java/hirs/swid/utils/CredentialArgumentValidator.java
tools/tcg_rim_tool/src/main/java/hirs/swid/utils/FileArgumentValidator.java

These changes include the following:
1. This block of text is printed following -c and -v functions only if --verbose is also given
Creating: base
Using attributes file: HIRS-issue_103-test-rim-configs/configs/Base_Rim_Config.json
Write to: 
Verify file: 
Truststore file: default (/opt/rimtool/data/keystore.jks)
Event log support RIM: HIRS-issue_103-test-rim-configs/eventlogs/TpmLog.bin
No timestamp included
Unrecognized command line options will cause the rimtool to exit, and all unrecognized options will be printed.
2. Error messages will be logged instead of printed to console, and and exit code of 1 will be returned.
These changes will also check that the proper credential arguments are given, and log appropriate errors if not.
Close #661 
Close #692

[#661] Output handling should be more concise

---

.ci/docker/Dockerfile.aca-rocky
.ci/docker/Dockerfile.aca-windows
.github/workflows/create_aca_images.yml

The dockerfiles were hard coded to build from main. These changes should allow the target branch to be built.

create_aca_images workflow passes branch ref to dockerfiles

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ComponentResultRepository.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/PolicySettings.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/ComponentResult.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentAttributeResult.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/SupplyChainValidationService.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/ValidationService.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/CredentialHelper.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/PciIds.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/CertificateAttributeScvValidator.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/CredentialValidator.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/PcrValidator.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/SupplyChainCredentialValidator.java
HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/validation/SupplyChainCredentialValidatorTest.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/PolicyPageModel.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IndexPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PolicyPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/policy.jsp

This is a combined PR for #732 and #730.  There is a linger issue that will be noted in #705 with the delta comparison.
This is a continuation of the PR for #723  and issue #705 . These changes set up fixing the delta part of the provisioning of the attributes.
This is the second part which covers the delta portion of this code.
Issue #707 from 
PR #732 
Added UI features and back end code to handle the new policy which doesn't include the revision comparison as part of the final validation pass/fail.
this closes #707

[#707 #705] Delta Component compare part 2 and Policy Addition

---

HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
settings.gradle
tools/tcg_rim_tool/src/main/java/hirs/swid/Main.java
tools/tcg_rim_tool/src/main/java/hirs/swid/utils/Commander.java
tools/tcg_rim_tool/src/main/java/hirs/swid/utils/CreateArgumentValidator.java
tools/tcg_rim_tool/src/main/java/hirs/swid/utils/VerifyArgumentValidator.java
tools/tcg_rim_tool/src/test/java/hirs/swid/TestSwidTagGateway.java

These changes require a public signing certificate for `rim --verify` operation.  The cert is used to check the <KeyName> value in the signature, and then to check the truststore's validity.  Major changes include:
- New VerifyArgumentValidator class to require `-p|--public-certificate` with `-v|--verify`
- Modified ReferenceManifestValidator class to implement checks with public signing cert
- Upgrade JCommander
Closes #726

[#726] Verify base RIM signature against truststore using public signing cert

---

.ci/docker/Dockerfile.aca-rocky

The entry command for the ACA image needed to be updated to point to scripts now under package/linux.

Dockerfile.aca-rocky needed to update its launch command to new package scripts folder

---

HIRS_AttestationCAPortal/src/main/resources/application.properties

Modifies `application.properties` to allow GZIP compression on Tomcat, which should substantially reduce the size of ACA portal content. Closes #745.

[#745] Adding GZIP compression to Tomcat server

---

HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/report/DeviceInfoReportTest.java
HIRS_AttestationCA/src/test/resources/VERSION
HIRS_Utils/src/test/java/hirs/utils/VersionHelperTest.java
HIRS_Utils/src/test/resources/VERSION

Closes #759 
Currently DeviceInfoReportTest is not passing due to a change in how version is implemented. This fix was originally a part of PR https://github.com/nsacyber/HIRS/pull/742 but due to that PR being on hold, moving this to its own PR.
Changes to fix error in unit test in DeviceInfoReportTest:
- HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/report/DeviceInfoReportTest.java
- HIRS_AttestationCA/src/test/resources/VERSION (removed)
- HIRS_Utils/src/test/java/hirs/utils/VersionHelperTest.java
- HIRS_Utils/src/test/resources/VERSION (removed)

Fixed issue in DeviceInfoReportTest

---

tools/tcg_eventlog_tool/build.gradle

Creates a "Fat jar" for running without linking in HIRS_Utils.jar for the tcg_eventlog_tool.

updated build to include HIRS_UTILS

---

HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureData.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiX509Cert.java
tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java

When eventlog tool is run as user (such as in a command prompt without sudo, or in an IDE which is run as the user), the vendor-table.json file is not accessible, and so valid GUID lookups return "unknown GUID reference". In some cases the code needs this GUID reference to determine the next piece of code that executes. If the GUID is valid but the code thinks it is invalid, it will not process the next chunk of data properly. 
This PR covers Change # 1 in the below. 
Changes needed:
1) do not process code with an unknown SignatureType in EFI_SIGNATURE_TYPE
2) when grabbing the file vendor-table.json from /etc/hirs/aca/default-properties/vendor-table.json, if the file is not accessible, then grab the file from code: /HIRS_AttestationCA/src/main/resources/vendor-table.json
Potential …

Event processing when no access to vendor-table.json Part 1/2

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/BaseReferenceManifest.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
HIRS_AttestationCAPortal/build.gradle
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/error.jsp
HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
HIRS_Utils/src/main/java/hirs/utils/swid/SwidTagConstants.java
HIRS_Utils/src/main/java/hirs/utils/xjc/ObjectFactory.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagConstants.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java

These changes comprise the following:
- properly prefix Directory, File, and TimeStamp in RIMs generated by rimtool
- properly handle namespace prefixes during validation
- properly handle multi-file uploads of support and base RIMs
Closes #737 
Closes #770

[#737] Resolve RIM upload parse error

---

.ci/docker/Dockerfile.aca-rocky-ci
.ci/docker/Dockerfile.tpm2provisioner-dotnet-ci
.ci/docker/docker-compose-system-test.yml
.ci/system-tests/run_system_tests.sh
.github/workflows/system_test.yml

This PR is meant to add an ACA container built from Rocky 9 specifically meant for System Tests in the CI. It also follows up on [PR 748](https://github.com/nsacyber/HIRS/pull/748) to make minor additions to suit the new ACA containers, plus some improved comments and one renamed file.
The following files have been added/modified:
- `Dockerfile.aca-rocky-ci` is the Dockerfile used to create an image for the ACA built from Rocky 9, specifically to be used with the CI System Tests. It differs from `Dockerfile.aca-rocky` by NOT using a CMD statement at the end of the Dockerfile (it is now commented out) to start the ACA; instead, the ACA scripts are called from `run_system_tests.sh`. However, if the user wanted to use the CMD statement and use the container for other purposes, they can …

[#765] Adding ACA Rocky Container for CI System Tests

---

tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java

These changes generate timestamp elements that pass validation:
`<SignatureProperty Id="TST" Target="RimSignature">`
`          <rcf3339:TimeStamp xmlns:rcf3339="https://www.ietf.org/rfc/rfc3339.txt" rcf3339:dateTime="2024-06-19T08:35:20.000Z"/>`
`</SignatureProperty>`
Closes #789

Modify rimtool to properly namespace timestamp elements

---

HIRS_Provisioner.NET/hirs/src/provisioner/Provisioner.cs

Saves the attestation certificate generated by the provisioner to the local file system. Closes #787.

[#787] Saving attestation certificate to file

---

HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TpmPcrEvent.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEvent.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventData.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventData2.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataDeviceContext.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataHeader.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataHeader2.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataSubHeader.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataSubHeaderSpdmMeasurementBlock.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventHeader.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiSpdmDeviceSecurityEvent.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmMeasurement.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmMeasurementBlock.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java

Closes #793 
Added these data structures for SPDM events:
DEVICE_SECURITY_EVENT_DATA2
DEVICE_SECURITY_EVENT_DATA_HEADER2
DEVICE_SECURITY_EVENT_DATA_SUB_HEADER
DEVICE_SECURITY_EVENT_DATA_SUB_HEADER_SPDM_MEASUREMENT_BLOCK
Made updates to other SPDM data structures to be more clear/ better designed

Add SPDM Events Part 3

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/SupportReferenceManifest.java

This change resolves the error
`ERROR : Null value was assigned to a property [class hirs.attestationca.persist.entity.userdefined.rim.SupportReferenceManifest.processed] of primitive type : hirs.attestationca.persist.entity.userdefined.rim.SupportReferenceManifest.processed (setter)`
This change also removes the column processed from the ReferenceManifest backend table.
Closes #797

[#797] Remove SupportReferenceManifest.processed

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/AcaPciIds.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/CertificateAttributeScvValidator.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
HIRS_Utils/build.gradle
HIRS_Utils/src/main/java/hirs/utils/PciIds.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataPciContext.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventHeader.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiDevicePath.java
tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java

Closes #757 
The class PciIds is in AttestationCA. However, a few functions in PciIds are needed to process SPDM event log structures defined in the PFP (specifically DEVICE_SECURITY_EVENT_DATA_PCI_CONTEXT), and the event log classes are in Utils. PciIds class cannot be accessed from Utils without creating a circular dependency. 
1) renamed AttestationCA pciids to AcaPciIds
2) created a Utils PciIds and moved the DB object, the vendor id and device id translate functions in AcaPciIds into Utils PciIds
3) updated DeviceSecurityEventDataPciContext to use PciIds to report Vendor and Device IDs
4) update Utils PciIds to also translate classcode, and update DeviceSecurityEventDataPciContext to use this feature

Move part of PciIds from AttestationCA back to Utils

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/SupplyChainValidation.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/ValidationService.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java

These changes accomplish the following toward properly displaying PCR mismatches in the ACA:
- flag firmware failures due to eventlog measurements
- pull EventMeasurement rim data in response to the above failures
Closes #807

[#807] Display PCR comparison table for mismatches

---

HIRS_Utils/src/main/java/hirs/utils/HexUtils.java
HIRS_Utils/src/main/java/hirs/utils/JsonUtils.java
HIRS_Utils/src/main/java/hirs/utils/PciIds.java
HIRS_Utils/src/main/java/hirs/utils/enums/DeviceInfoEnums.java
HIRS_Utils/src/main/java/hirs/utils/swid/SwidTagConstants.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvConstants.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvNoAction.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/NvIndexDynamicEventLogData.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/package-info.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmHa.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/package-info.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiConstants.java
HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/package-info.java
HIRS_Utils/src/main/java/hirs/utils/tpm/package-info.java

Closes #820 
EV_EFI_NOACTION has a structure of NvIndexDynamic which was implemented here. This is used for various SPDM calls.
Also added empty private constructors to several utility classes to appease checkstyles.

Add processing for EV_EFI_NOACTION NvIndexDynamic structure

---

HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
HIRS_Provisioner.NET/hirsTest/hirsTest.csproj

Closes #791 #837 
1. Install the .NET 8 SDK as [described by Microsoft](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) for your platform.
2.  Check out the repository 
2.a.  Ex: ```git clone https://github.com/nsacyber/HIRS.git```
3. cd HIRS_Provisioner.NET
3.a. Set up build ```dotnet restore```
3.b. Build & Test ```dotnet test```
4. cd HIRS_Provisioner.NET/hirs
5. If interested in building an RPM or DEB file for linux, install dotnet 
5.a. ```dotnet tool install --global dotnet-deb```
5.b. ```dotnet tool install --global dotnet-rpm```
6. Create desired installation package <b>MSI building only works on Windows</b>
6.a. <b>MSI</b> ```dotnet msbuild hirs.csproj /t:Msi /P:TargetFramework=net8.0 /p:RuntimeIdentifier=win-x64 /p:Configuration=Release```
6.b. <b>Linux RPM</b> ```dotnet …
```

Provisioner will use .NET 8

---

.github/workflows/dotnet_provisioner_unit_tests.yml

actions/upload-artifact@v2 was removed. Now using v4.
actions/checkout@v3 was giving a warning. Now using v4.
Still get a warning on set-output. Can fix that another time.

dotnet_provisioner_unit_tests workflow will use newer actions

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java

The two main changes included here are:
1. delete the RIM from the backend table when /delete is called instead of archiving
2. if an archived RIM is returned for FW validation then attempt to return an unarchived RIM with matching identifiers.
This PR also attempted to address the use cases where a good or bad RIM bundle is sent with an initial provision and then replaced by the other.  This grew beyond the scope of this PR and will be handled in a future issue.
Closes #808

[#808] Retrieve unarchived RIM bundle for provision

---

HIRS_Structs/build.gradle
HIRS_Structs/config/spotbugs/spotbugs-exclude.xml
HIRS_Structs/src/main/java/hirs/structs/converters/SimpleStructBuilder.java
HIRS_Structs/src/main/java/hirs/structs/converters/SimpleStructConverter.java
HIRS_Structs/src/main/java/hirs/structs/converters/StructConverter.java
HIRS_Structs/src/main/java/hirs/structs/elements/StructElementLength.java
HIRS_Structs/src/main/java/hirs/structs/elements/StructElements.java
HIRS_Structs/src/main/java/hirs/structs/elements/aca/IdentityRequestEnvelope.java
HIRS_Structs/src/main/java/hirs/structs/elements/aca/IdentityResponseEnvelope.java
HIRS_Structs/src/main/java/hirs/structs/elements/aca/SymmetricAttestation.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/AsymmetricKeyParams.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/AsymmetricPublicKey.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/EncryptionScheme.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/IdentityProof.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/IdentityRequest.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/PublicKey.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/RsaSubParams.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/StorePubKey.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/SymmetricKey.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/SymmetricKeyParams.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/SymmetricSubParams.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/Version.java
HIRS_Structs/src/test/java/hirs/structs/converters/SimpleStructBuilderTest.java
HIRS_Structs/src/test/java/hirs/structs/converters/SimpleStructConverterTest.java
HIRS_Structs/src/test/java/hirs/structs/converters/TestEmbeddedStruct.java
HIRS_Structs/src/test/java/hirs/structs/converters/TestInvalidDataTypeStruct.java
HIRS_Structs/src/test/java/hirs/structs/converters/TestStruct.java
HIRS_Structs/src/test/java/hirs/structs/converters/TestVariableStruct.java

[Checkstyle](https://github.com/checkstyle/checkstyle/tree/master) is used for meeting best practices for java code styling. All classes in HIRS_Structs should be updated to pass checkstyle tests being run by gradle.
1. Follow steps 1 - 3 in this previous pull request: https://github.com/nsacyber/HIRS/pull/846to confirm you can save and apply checkstyle recommended styling changes to your code in your favorite IDE.
2. Run the command below to confirm that all the checkstyle errors for the HIRS_STRUCTS module have been fixed:
` ./gradlew clean HIRS_Structs:check --rerun-tasks`
3. .Run the command below to confirm that there are no issues building or running tests for the entire application:
`./gradlew clean build --rerun-tasks`
4. If you were able to run all the commands without running …

[#873] Fixed Checkstyle Issues In HIRS_STRUCTS

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java

The following identifiers have been refactored as of the first push:
IdentityClaimProcessor
- dbBaseRim -> baseRim
- support -> supportRim
- measurements -> integrityMeasurements
- sourcedValues -> expectedValues
- logProcessor -> eventLog
FirmwareScvValidator
- tcgMeasurementLog -> eventLog
- tpmPcrEvents -> failedPcrValues
Testing entails running a firmware provision as usual to make sure these name changes do not cause any logic differences.  The new names should be reviewed against the tcg documentation for accuracy.
Closes #848

[#848] Rename properties and methods of firmware validation objects

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/PcrValidator.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java

These changes follow those from #848.  It should be noted that after reviewing the documentation the ReferenceDigestValue class was deemed appropriately named and _not_  renamed as originally intended.  Variable names in a few other classes have been refactored to more clearly align with TCG documentation.  More checkstyle changes have been implemented as well.
Closes #879

[#879] Additional renaming and checkstyle  changes

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/info/TPMInfo.java
HIRS_Structs/src/main/java/hirs/structs/elements/aca/IdentityRequestEnvelope.java
HIRS_Structs/src/main/java/hirs/structs/elements/aca/IdentityResponseEnvelope.java
HIRS_Structs/src/main/java/hirs/structs/elements/aca/SymmetricAttestation.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/AsymmetricKeyParams.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/AsymmetricPublicKey.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/IdentityProof.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/IdentityRequest.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/PublicKey.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/RsaSubParams.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/StorePubKey.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/SymmetricKey.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/SymmetricKeyParams.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/SymmetricSubParams.java
HIRS_Structs/src/main/java/hirs/structs/elements/tpm/Version.java
HIRS_Structs/src/test/java/hirs/structs/converters/TestEmbeddedStruct.java
HIRS_Structs/src/test/java/hirs/structs/converters/TestStruct.java
HIRS_Utils/src/main/java/hirs/utils/xjc/SoftwareIdentity.java
tools/tcg_rim_tool/src/main/java/hirs/swid/CredentialParser.java
tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java

Look for Java classes that use your typical setters and getters and replace those setters/getters with the Lombok annotations. 
Closes https://github.com/nsacyber/HIRS/issues/872

[#872] Apply Lombok to Remaining Classes with Boilerplate Code

---

.github/workflows/dotnet_provisioner_unit_tests.yml
.github/workflows/hirs_unit_tests.yml

CI builds are failing because upload-artifact v3 is deprecated; upated to v4.

Updated to upload-artifact@v4

---

HIRS_AttestationCA/build.gradle
HIRS_AttestationCAPortal/build.gradle
HIRS_Structs/build.gradle
HIRS_Utils/build.gradle
gradle/versions.toml
tools/tcg_rim_tool/build.gradle

We found out recently that the HIRS log file is not only not recording any activities that are occurring in the application but that it is located in a completely directory.
1. Run the application either by creating an RPM/Debian file or using the setup scripts located in the package/linux/aca folder.
2. You can upload a bunch of PEM/CER files to the pages that allow you to upload certificates (such as the Trust Chain Management page) or even the Platform Certificate page and run the `sudo tpm_aca_provision` command. Pretty much try to perform some basic activities on the application
3. Go to the `/var/log/hirs `directory and verify that the `HIRS_AttestationCA_Portal.log` log file is there and open it up in your favorite code editor.
4. Verify that all the activities that you performed …

[#901] HIRS Application Log File Is Empty/Not Found In Correct Directory

---

.github/workflows/dotnet_provisioner_unit_tests.yml
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/CredentialHelper.java

This change should tell the ACA to take only the first certificate in a PEM file.
Also saw GitHub Actions was removing the ubuntu 20 runner. Pointed one of the workflows to a newer runner.

Take only first cert in multi part PEM

---

.github/workflows/create_aca_images.yml

Reverts the ACA docker image workflow to use v3.

docker login action v4 does not exist yet

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/RestfulAttestationCertificateAuthority.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/CertificateService.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/PersistenceJPAConfig.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/TrustChainCertificatePageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/ControllerPagesUtils.java
HIRS_AttestationCAPortal/src/main/resources/application.properties
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/trust-chain.jsp
HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/PageControllerTest.java
HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/PageTestConfiguration.java
HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/TrustChainManagementPageControllerTest.java

This ticket focuses on allowing the ACA the ability to download the Certificate Trust Chain (Root, intermediate, and all leaf certificates).
1. Run the ACA using your preferred method: bootrun, docker, or using an installed RPM.
2. Head on over to the Trust Chain Management page and click on the clipboard icon next to the words **HIRS Attestation Certificate Chain**.
3. Verify that it displays a new title **HIRS Attestation Root Certificate**.
4. Back out of the modal window and click on the download icon.
5. Verify that the browser downloads a PEM file that contains 3 certificates.
6. Open up the PEM file and confirm that the ACA's leaf certificate, intermediate certificate and root certificate are all in there.
Closes https://github.com/nsacyber/HIRS/issues/821

[#821] HIRS Attestation ACA  Should Download ACA Certificate chain

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/ValidationSummaryReportsService.java
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/validation-reports.jsp

This PR fixes a bug that caused a 404 error when attempting to download the validation report CSV file.
1. Run the ACA using your preferred method: bootrun, docker, or using an installed RPM.
2. Head on over to the Validation Reports page and click on the download icon.
3. Fill out the "form" however you like and click on save.
4. Verify that a csv is downloaded and that the page no longer displays a 404 error.
5. Verify that the CSV shows the device system information and the device's components' info in a csv format.
Closes #922

[#922] Fixed 404 Error When Downloading Validation Report

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/RestfulAttestationCertificateAuthority.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/CertificateRequestProcessor.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/HelpPageService.java

Save key information such as the Identity Claim, Identity Claim response, Certificate Request and Certificate Request response to the ACA Log during the provisioning process.
1.Run the HIRS Application.
2. Go to the help page and search for IdentityClaimProcessor, CertificateRequestProcessor and RestfulAttestationCertificateAuthority and set each file's logger to debug mode.
3. Open a terminal window and run the following command to view the aca log in real time: `sudo tail -f /var/log/hirs/HIRS_AttestationCA_Portal.log`
4. Open another new terminal window and run the command `sudo tpm_aca_provision`
5. Verify that while the proviosining is occurring, you can see the four objects we are looking for in the aca log.
Closes https://github.com/nsacyber/HIRS/issues/926

[#926] Save PROTOBUF Data To ACA Log

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/SupplyChainValidationService.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/PcrValidator.java
HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java

Updated the ACA to report a more useful error when signature validation fails because an issuer cert is missing.
Closes #940 
Closes #948

[#940] Update error message for RIM signature validation failure

---

HIRS_AttestationCAPortal/src/main/resources/application.win.properties
HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java

The logs from some of the Windows-based Docker containers indicate that certain newly created properties from PR https://github.com/nsacyber/HIRS/pull/931 are not being properly initialized, preventing the containers from functioning as expected.
Closes #956

[#956] ACA Properties Not Initialized In Window Docker Containers

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Certificate.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/CertificateVariables.java

Increase the length of the Certificate Bytes column definition to ensure that large Certificates can be uploaded to the ACA.
1. Download the latest and greatest version of paccor (vbeta3) https://github.com/nsacyber/paccor/releases/tag/v1.5.0beta3 to your Linux device.
2. If you're using a tar file, extract the tar file and head over to the scripts directory and find the pc_certgen.sh script. (If you decided to take the install rpm or debian file route, head over to the `/opt/paccor/scripts`.
3. Once you find the script,  run the `pc_certgen.sh`  script in sudo mode: 
```
sudo ./pc_certgen.sh
```
4. Make sure that you find an endorsement credential and a newly minted platform certificate in the pc_testgen directory. I would highly suggest copying the certs over to your home directory and …

[#979]: Lengthen Certificate Bytes Column Definition

---

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/CertificateService.java
HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/HelpPageService.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/EndorsementCredentialPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/HelpPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IDevIdCertificatePageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IssuedCertificatePageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PlatformCredentialPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/TrustChainCertificatePageController.java
HIRS_AttestationCAPortal/src/main/resources/application.properties
HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/help.jsp

This issue aims to enhance the functionality of the download button on the help page by enabling users to download a single ZIP archive containing all HIRS Attestation log files available in the logs directory. This improvement will provide users with easier access to historical log data directly from the GUI.
1. Run the ACA using your preferred method.
2. Head over to the Help page and click on the download icon next to where it says **Download All HIRS Logs**.
3. Verify that the browser downloads a zip file that contains one or more HIRS Attestation log files.
4. Verify that you can open each file and you can read each file's content.
Closes #1002

[#1002]  Add Ability To Download Multiple HIRS Log Files

---

HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/AttestationCertificateAuthorityTest.java

Use of SHA1PRNG is prevented when the RHEL device has FIPS mode enabled. ~~Switching to NativePRNG should allow the device to pull from sources (e.g. /dev/random) that are not disabled when FIPS mode is enabled~~. Had to move to java.util.random for the test to avoid issues with Java.security.SecureRandom in FIPS mode. This fix will build on FIPS enabled devices.
closes #984

[#984] Updated ACA Test pseudo random source
