nsacyber/HIRS

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java, HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java
This is a small merge request to allow for uploading of ECC certificate to the AttestationCA Portal.
Closes #1
=> [#1] Add support for processing ECC certificates as part of the trust chain

.travis.yml, Dockerfile, HIRS_Utils/src/test/java/hirs/data/persist/certificate/PlatformCredentialTest.java, build.gradle
This MR sets up a basic Travis CI build for the project. It creates a Docker image that's gets loaded with all the necessary dependencies and then runs all of the unit tests, style checks, static analysis, etc. that we normally expect should occur with every build.
Closes #12
=> [#12] Setup basic Travis CI build

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
This pull request forces the supply chain validation service to verify that the Platform Credential has a status of PASS.  If it does not, no matter the outcome of the Attributes validation, the status of the Attributes can not be PASS.  This has to do with the attributes passing with no platform certificate.
Fix for #21
=> [#21] Make the Platform Attributes validation check match Platform validation

.travis.yml, docker/Dockerfile.centos7, docker/Dockerfile.ubuntu18
This is a small merge request to update the Travis CI build to include package testing.
As part of this work, a new Docker image was created for Ubuntu 18.04 to support testing of `package.ubuntu.sh`.
Closes #32
=> [#32] Add package stage to Travis Build

HIRS_ProvisionerTPM2/include/CommandTpm2.h, HIRS_ProvisionerTPM2/include/Process.h, HIRS_ProvisionerTPM2/src/CommandTpm2.cpp, HIRS_ProvisionerTPM2/src/Process.cpp, HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp, HIRS_ProvisionerTPM2/src/Tpm2ToolsUtils.cpp
There were unnecessary references to file paths in the executable.
=> [#62] Cleaned up preprocessor file expansion.

HIRS_Provisioner/scripts/install/hirs-provisioner.sh, HIRS_ProvisionerTPM2/CMakeLists.txt, HIRS_ProvisionerTPM2/package/postinst, HIRS_ProvisionerTPM2/package/rpm-post-install.sh, HIRS_ProvisionerTPM2/src/tpm_version.cpp, HIRS_Utils/src/main/java/hirs/data/persist/TPMMeasurementRecord.java, HIRS_Utils/src/main/java/hirs/data/persist/tpm/PcrInfoShort.java, HIRS_Utils/src/main/java/hirs/data/persist/tpm/QuoteSignature.java
XML for TPM report can not hold raw TPM 2.0 quote.
Closes #99.
=> Updates to allow for TPM 2.0 quote.

HIRS_Utils/src/main/java/hirs/data/persist/AbstractDigest.java, HIRS_Utils/src/main/java/hirs/data/persist/DigestAlgorithm.java
Added length to DigestAlgorithm enum values.
Closes #124.
=> [#124] Added length to DigestAlgorithm enum values.

.ci/docker/Dockerfile.amazonlinux2, .ci/docker/Dockerfile.centos7, .ci/docker/Dockerfile.ubuntu18, HIRS_ProvisionerTPM2/CMakeLists.txt, HIRS_ProvisionerTPM2/docs/developer-dependencies-centos.md, HIRS_ProvisionerTPM2/docs/developer-dependencies-debian.md, HIRS_ProvisionerTPM2/src/tpm_version.cpp
The TPM 2 Provisioner gets packaged with an application called
tpm_version, which reported hard-coded values for the TPM
manufacturer and version. Now it collects those things from
the TPM and reports them.
Closes #105.
=> [#105] Updated tpm_version to get data from TPM hardware.

.ci/docker/Dockerfile.aca, .ci/docker/Dockerfile.amazonlinux2, .ci/docker/Dockerfile.centos7, .ci/docker/Dockerfile.tpm2provisioner, .ci/docker/Dockerfile.tpmprovisioner, .ci/docker/Dockerfile.ubuntu18
Self explanatory MR.
Closes #139
=> [#139] Remove Maintainer Tags from Dockerfiles

HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
Corrected misplaced jsp comment tags.
Closes #146
=> [#146] Updated the jsp to correct the comment tags for content and jsp tag.

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_AttestationCA/src/test/java/hirs/attestationca/service/SupplyChainValidationServiceImplTest.java, HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/CertificateDetailsPageControllerTest.java, HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java, HIRS_Utils/src/test/java/hirs/data/persist/certificate/PlatformCredentialTest.java
This fixes the issue of the delta certificate not being verified.  They simply were not being included in that part of the policy code.
Closes #163
=> [#163] Delta issuer validation

HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
This pull request is for the removal of an unnecessary loop that is meant to build a separate delta supply chain.
Closes #162
=> [#162] Attribute match fix

HIRS_Utils/src/main/resources/component-class.json
In review of the new revision 4 for the component class registry, there were a few changes that needed to be made and updated.
=> Minor Component Class update

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/validation-reports.jsp
After a series of system tests, there were corrections needed to the validation sort and store in the code.  This request fixes those issues.
=> [#181] Validation systemcheck fix

.ci/setup/addFaultyComponentsForPBaseCertB.py, .ci/setup/createDeltaComponentsForPBaseCertA.py, .ci/setup/createDeltaComponentsForPBaseCertB.py, .ci/setup/setup-tpm2provisioner-base-delta-bad.sh, .ci/setup/setup-tpm2provisioner-base-delta-good.sh, .ci/setup/setup-tpm2provisioner.sh, .ci/system-tests/run-system-tests-tpm2-base-delta-bad.sh, .ci/system-tests/run-system-tests-tpm2-base-delta-good.sh, .ci/system-tests/run-system-tests-tpm2.sh, .ci/system-tests/system_test.py, .ci/system-tests/system_test_Driver.py
Implemented remaining system tests.
=> [#176] Updated system tests from changes in latest Master build.

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp, HIRS_Utils/src/main/java/hirs/data/persist/certificate/IssuedAttestationCertificate.java, HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
Credential Type Label     MUST 
Public AIK  MUST 
TPM Model MUST
Platform Model MUST 
Issuer MUST
TPM Specification MUST 
Platform Specification  MUST 
Signature Value MUST 
Identity Label SHOULD 
TPM Assertions MAY 
Platform Assertions MAY 
Validity Period MAY
Policy Reference MAY 
Revocation Locator MAY 
From the TCG specification, these are the elements that should be associated with an AIC and their associated state.  Generally stuff that is labelled as MAY will not appear on the page as blank if they aren't available (the field is hidden), everything else will be listed but appear empty.
Closes #168
=> [#168] Additional fields added to the Issued AC

.ci/docker/docker-compose.yml, .ci/setup/setup-tpm2provisioner-base-delta-bad.sh, .ci/setup/setup-tpm2provisioner-base-delta-good.sh, .ci/setup/setup-tpm2provisioner.sh, .ci/setup/setup-tpmprovisioner.sh, .ci/system-tests/run-system-tests-tpm2-base-delta-bad.sh, .ci/system-tests/run-system-tests-tpm2-base-delta-good.sh, .ci/system-tests/run-system-tests-tpm2.sh, .ci/system-tests/run-system-tests.sh, .ci/system-tests/system_test.py, .ci/system-tests/system_test_Driver.py, .ci/system-tests/system_test_core.py, .ci/system-tests/systems-test-centos7-tpm1-2.sh, .ci/system-tests/systems-test.core.sh, .travis.yml, HIRS_Utils/src/main/java/hirs/utils/VersionHelper.java, HIRS_Utils/src/test/java/hirs/utils/VersionHelperTest.java
- Integrated TPM 1.2 emulator into the HIRS tpmprovisioner docker image.
- Added initial system tests for TPM 1.2 emulator:
test_01_attestation_ca_portal_online
test_13_tpm_1_2_initial_provision
=> [#88] Integrate System Tests with Dockerized TPM 1.2 Provisioner

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_Utils/src/main/java/hirs/data/persist/ArchivableEntity.java, HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainValidation.java, HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainValidationSummary.java, HIRS_Utils/src/main/java/hirs/data/persist/TPMMeasurementRecord.java, HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
Updated code to correctly match up the PCR to the baseline PCR. Also updated values of error messages and reduced firmware error message size being stored in the database.
=> Validation bug

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
#265 Will encompass adding options to skip validating specific PCRs.  This Pull Request adds a temporary skip of the IMA PCR for demoing purpose.  A follow up PR will be created following this.
=> [#265] Skip ima pcr

tools/scripts/eventcheck.sh, tools/scripts/identity_transform.xslt, tools/tcg_eventlog_tool/build.gradle, tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Commander.java, tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
Minor updates:
* changed package name to tcg_eventlog_tool.
* removed string output from -x options
* placed extra check for valid filter options
=> Change package name to tcg_eventlog_tool

HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
Added case statement for 2.23.133.2.25 just like for 2.23.133.2.17 so that the error isn't thrown.
Closes #266
=> [#266] Add Case statement for OID

.gitignore, tools/tcg_rim_tool/package.sh, tools/tcg_rim_tool/scripts/rimtool.sh, tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java, tools/tcg_rim_tool/src/main/java/hirs/swid/utils/HashSwid.java, tools/tcg_rim_tool/src/test/java/hirs/swid/TestSwidTagGateway.java, tools/tcg_rim_tool/src/test/resources/generated_no_cert.swidtag, tools/tcg_rim_tool/src/test/resources/generated_with_cert.swidtag, tools/tcg_rim_tool/tcg_rim_tool.spec
This push adds a symlink under /usr/local/bin/rim to the script file installed at /opt/hirs/rimtool.
Closes #268
=> [#268] Tcg_rim_tool symlink

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp, HIRS_Utils/src/main/java/hirs/data/persist/SwidResource.java
Updated RIM Details page to display File Not Found when the associated event log has not been uploaded with the swid tag.
Closes #274
=> [#274] Swid Resource Not Found

HIRS_Utils/src/main/java/hirs/tpm/eventlog/events/EvEfiBootServicesApp.java
minor adjustment to remove "unmappable" character. 
Closes #287
=> [#287] removed unmappable characters from comment lines

tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java, tools/tcg_rim_tool/src/test/resources/generated_no_cert.swidtag, tools/tcg_rim_tool/src/test/resources/generated_with_cert.swidtag, tools/tcg_rim_tool/src/test/resources/rim_fields.json
=> [#295] Move supportRIMFormat from Meta to Payload

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_AttestationCAPortal/config/checkstyle/suppressions.xml, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/datatables/DataTableResponse.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/reference-manifests.jsp, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp, HIRS_AttestationCAPortal/src/main/webapp/common/certificate_details.css, HIRS_AttestationCAPortal/src/main/webapp/common/rim_details.css, HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageControllerTest.java, HIRS_ProvisionerTPM2/src/CommandTpm2.cpp, HIRS_Utils/src/main/java/hirs/data/persist/BaseReferenceManifest.java, HIRS_Utils/src/main/java/hirs/data/persist/PCRPolicy.java, HIRS_Utils/src/main/java/hirs/data/persist/ReferenceManifest.java, HIRS_Utils/src/main/java/hirs/data/persist/SupportReferenceManifest.java, HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java, HIRS_Utils/src/main/java/hirs/persist/ReferenceManifestSelector.java, HIRS_Utils/src/main/java/hirs/tpm/eventlog/TCGEventLog.java, HIRS_Utils/src/main/java/hirs/tpm/eventlog/TpmPcrEvent.java, HIRS_Utils/src/main/java/hirs/tpm/eventlog/events/EvPostCode.java, HIRS_Utils/src/main/java/hirs/tpm/eventlog/uefi/UefiFirmware.java, tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
This request closes the issue that adds a details page for the support base reference integrity manifest .
Closes #280
=> [#280] Base/Support RIM display enhancements

HIRS_Utils/src/main/resources/component-class.json
Component Class json file updated to latest revision.
=> Updated the Component Class Registry to rev. 4

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
This PR addresses the bugs identified in #314.  Due to previous changes to the RIM upload process, the support RIM was not being updated properly when manually uploaded.
Closes #314
=> [#314] Support RIM bug fixes

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
=> [#318] RIM upload error

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_ProvisionerTPM2/include/Utils.h, HIRS_ProvisionerTPM2/package/rpm-post-install.sh, HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp, HIRS_ProvisionerTPM2/src/Utils.cpp, HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
The current provisioner uploads a platform certificate that is stored in the TPM.  This change will, in addition to pulling from the tpm, pull from a boot sector if the tpm doesn't have a platform certificate.  The change grabs all files from the specified location and sends them to the ACA.
=> Platform Certificate Upload Modification

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java, HIRS_ProvisionerTPM2/include/Utils.h, HIRS_ProvisionerTPM2/package/rpm-post-install.sh, HIRS_ProvisionerTPM2/src/ProvisionerTpm2.proto, HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp, HIRS_ProvisionerTPM2/src/Utils.cpp
This pull request changes the way the provisioner pulls swidtags and rimel files.  Instead of a specific file being targeted by the post install script, the directories are saved and the provisioner pulls everything in those directories.
=> Multiple RIM upload

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp, HIRS_AttestationCAPortal/src/main/webapp/common/rim_details.css
=> [#329] Firmware Tests summary

HIRS_ProvisionerTPM2/CMakeLists.txt, HIRS_ProvisionerTPM2/include/HirsRuntimeException.h, HIRS_ProvisionerTPM2/src/CommandTpm2.cpp
Corrected method definition mismatch and added a suppress rule.
=> CppCheck cleanup

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/validation-reports.jsp, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/tags/download-info.tag
These changes add a download link to the validation report page.  This link displays a dialog to collect some user input, pulls data corresponding to the validation report, and combines all the above into a file written locally to the client.
Closes #281
=> Validation report file

HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
This change is to update the code to the values listed in Table 13 of Registry of Reserved TPM 2.0 Handles and Localities for Platform Class Values.
=> Platform Class Values Update

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp, HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java, HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java, HIRS_Utils/src/test/java/hirs/data/persist/certificate/CertificateTest.java, HIRS_Utils/src/test/java/hirs/data/persist/certificate/PlatformCredentialTest.java, HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java
Updated the isIssuer and the containsAll to allow the reason for the platform certificate failure isn't that the issuer is missing but that the issuer available fails the public key on the details page for certificates
=> Certificate Failure Fidelity

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/model/PolicyPageModel.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PolicyPageController.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/policy.jsp, HIRS_Utils/src/main/java/hirs/data/persist/PCRPolicy.java, HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainPolicy.java
This set of code adds an additional policy to the page for the GPT PCR.  Details for the change can be found in issue #349.
=> [#349] Ignore GPT PCR

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java, scripts/download_validation_reports.sh
This pull request changes download_validation_reports.sh and ValidationReportsPageController class to support new options on the command line for modifying the downloaded report.
Closes #354
=> Support new command line options for validation report download

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java, scripts/download_validation_reports.sh
This pull request adds support for a -j|--json argument to the command line script.  Invoking it will download validation report data from the ACA in JSON format and incorporate the --start-date, --end-date, and --ip filters.
Closes #355
=> [#355] Download validation reports in JSON format

HIRS_ProvisionerTPM2/include/Process.h, HIRS_ProvisionerTPM2/src/CommandTpm2.cpp, HIRS_ProvisionerTPM2/src/Process.cpp
Fixes an issue with Process dropping a trailing '0a' byte when its response should contain binary data.
=> Fixed an issue that caused Process to drop data

tools/tcg_rim_tool/src/main/java/hirs/swid/utils/HashSwid.java, tools/tcg_rim_tool/src/test/resources/generated_no_cert.swidtag, tools/tcg_rim_tool/src/test/resources/generated_with_cert.swidtag
Revert "Add validation of base64 encoding for payload file hash attribute."
This reverts commit 51b92f7673f7475c0a6eccb90ce0c06d794a18a5.
Closes #364
=> [#364] Undo changes from issue-359

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/PciIds.java, HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentClass.java, HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java, HIRS_Utils/src/test/java/hirs/data/persist/certificate/attributes/ComponentClassTest.java
All components were failing on tests specifically set up to match components and pass.  This happened because the int value of the component class value was being translated with SHORT.size.  This is odd because it worked before but stopped.
=> Component Class Bug Fix

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_AttestationCA/src/test/java/hirs/attestationca/service/SupplyChainValidationServiceImplTest.java
Fixed a couple of errors in SupplyChainValidationServiceImpl.java
Mocked objects used in tests within SupplyChainValidationServiceImplTest.java required additional context due handling of delta platform certificates.
=> Updates to AttestationCA unit tests

HIRS_AttestationCAPortal/build.gradle
Ensured a compatible servlet will be on the classpath. The file can probably be cleaned up further.
=> Update Portal servlet

HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java, HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java
Refactor to account for any order of objects in additionalCerts parameter. 
Closes #386
=> [#386] Update overloaded validateCertChain to check cert chain consistently

HIRS_Utils/src/main/java/hirs/tpm/eventlog/events/EvEfiHandoffTable.java, HIRS_Utils/src/main/java/hirs/tpm/eventlog/uefi/UefiGuid.java, HIRS_Utils/src/test/java/hirs/data/persist/certificate/attributes/ComponentClassTest.java, HIRS_Utils/src/test/java/hirs/tpm/eventlog/events/TCGEventLogEventsTest.java
Updated the UefiGuid to have the vendor json file get passed in.  This updates the unit test and fixes the issue.
=> UEFI Unit Test Update

HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/model/PolicyPageModel.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PolicyPageController.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/policy.jsp, HIRS_Utils/src/main/java/hirs/data/persist/PCRPolicy.java, HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainPolicy.java
This code change updates the code to include new policy settings to ignore PXE events outlined in #404 .  
This pull request also revises the changes made in #349.
=> [#404] PXE Policy options

HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
Closes #414 
Tested this on a few devices.
It will allow component information to be modified if they don't have a serial number. The manufacturer, model and component class (value only for now) must be identical to match. Additionally, there must be only one component that matches. The other fields of the componentidentifier become modifiable. This also allows a delta cert to add a serial number to a component that didn't have one previously.
=> [#414] Handle MODIFIED component without serial number

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateRequestPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/endorsement-key-credentials.jsp, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/issued-certificates.jsp, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/platform-credentials.jsp, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/reference-manifests.jsp, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/trust-chain.jsp
This initial commit adds the ability to download all platform credentials and trust chain credentials from their respective pages in a bulk zip.
This will be updated to also include bulk downloads for RIMs.
=> Bulk Certificate Download

HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/policy.jsp
Temporary removal of policy page option for LDevID generation.
=> Policy Page update

HIRS_Utils/src/main/java/hirs/data/persist/certificate/CertificateAuthorityCredential.java, HIRS_Utils/src/main/java/hirs/utils/ReferenceManifestValidator.java, HIRS_Utils/src/test/java/hirs/data/persist/certificate/CertificateTest.java
Updated the CA certificate to truncate the prefix of the subject key identifier
=> Truncate 4 bytes from SKI

NOTICE
This updates the NOTICE to include additional Apache and MIT licences.
=> updated the NOTICE file

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
Added a null pointer check to the parsing of the support RIM section that looks to use the platform manufacturer and model fields to search for a Base RIM when those values are null.
Closes #468
=> [#468] Platform Manufacturer causes 500 error

tools/tcg_eventlog_tool/build.gradle, tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Commander.java, tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
Updates the tcg_eventlog tool for centos 7:
Fixes invocation when run by root user
Output option tested
Default options updated
Help file updated
closes issue-465
=> Updates the tcg_eventlog_tool

HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp, HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/TBBSecurityAssertion.java
Makes FIM Platform Assertions visible on the Platform Certificate details page.
=> [#515] FIM Assertions visible on cert details page

HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/rest/RestfulAttestationCertificateAuthority.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java, HIRS_AttestationCA/src/test/java/hirs/attestationca/AbstractAttestationCertificateAuthorityTest.java, HIRS_AttestationCA/src/test/java/hirs/attestationca/service/SupplyChainValidationServiceImplTest.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateDetailsPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/persistence/PersistenceConfiguration.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp, HIRS_AttestationCAPortal/src/main/webapp/common/certificate_details.css, HIRS_Utils/src/main/java/hirs/data/persist/certificate/ComponentResult.java, HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java, HIRS_Utils/src/main/java/hirs/persist/ComponentResultManager.java, HIRS_Utils/src/main/java/hirs/persist/DBComponentResultManager.java, HIRS_Utils/src/main/java/hirs/persist/DBReferenceEventManager.java, HIRS_Utils/src/main/java/hirs/persist/PersistenceConfiguration.java, HIRS_Utils/src/main/java/hirs/validation/CredentialValidator.java, HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java, HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java
Fixed up the changes for the first bullet point.  
However the second bullet needs more work and will be handled in a later fix.
Closes #511
=> [#511] Minor appearance update fixes

.ci/system-tests/sys_test_common.sh, package/scripts/common/secure_mysql.sql
removed setting sql root pwd during ACA install to allow for uninstall
=> removed setting sql root pwd during ACA install to allow for uninstall

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/platform-credentials.jsp, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp
Added download method mapper for certificates
#534 item 3 resolution
=> [#534] Fix for Downloading Certificates

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CACredentialRepository.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CertificateRepository.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/EndorsementCredentialRepository.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/IssuedCertificateRepository.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/PlatformCertificateRepository.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Certificate.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/PersistenceJPAConfig.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/datatables/OrderedListQueryDataTableAdapter.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateDetailsPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/RimDatabasePageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
This check in updates the code to list the certificates on their specific page, rather than all on any of them.  Next will be introducing the new parsing code for RIM and TLS so that Trust Chains show up
This covers 1. on the issue #534 
The amount of changes was growing so this is a stable push.  Next will be to resolve the displaying of RIMs and that is a part of #517 and next implementing the TLS for Trust Chain list displaying.
=> [#534] Updated display code

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/PersistenceConfiguration.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
For embedded tomcat, removed the file store service bean autowire because of configuration error.
=> Filestore Service Removal

.github/workflows/hirs_unit_tests.yml, .github/workflows/package_centos.yml, .github/workflows/system_test.yml
Completes issue 536
closes: #536
=> [#536] Adds Action filters to the main branch

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/AbstractEntity.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceManifestRepository.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentClass.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/BaseReferenceManifest.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/SupplyChainValidationServiceImpl.java, HIRS_AttestationCA/src/main/resources/identity_transform.xslt, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/PersistenceJPAConfig.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java, HIRS_Utils/src/main/java/hirs/utils/BouncyCastleUtils.java, HIRS_Utils/src/main/java/hirs/utils/SwidResource.java, HIRS_Utils/src/main/java/hirs/utils/swid/SwidTagConstants.java
the DN compare of bouncy castle utils throws and exception if the object is null.  Added additional condition to the if statement to check null status.
#534
=> [#534] Base RIM Details Page

tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagConstants.java, tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java, tools/tcg_rim_tool/src/test/resources/generated_default_cert.swidtag, tools/tcg_rim_tool/src/test/resources/generated_timestamp_rfc3339.swidtag, tools/tcg_rim_tool/src/test/resources/generated_timestamp_rfc3852.swidtag, tools/tcg_rim_tool/src/test/resources/generated_truststore_embed.swidtag, tools/tcg_rim_tool/src/test/resources/generated_user_cert.swidtag, tools/tcg_rim_tool/src/test/resources/generated_user_cert_embed.swidtag, tools/tcg_rim_tool/src/test/resources/rim_fields.json
These changes comprise the following:
- constant values updated to proper camel case
- non-required values are printed to console if they are not read in from json properties file
- updated unit tests
Closes #529
=> [#529] Fix attribute camel case

HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
@ResponseBody was removed by mistake and causes ajax dataTables error.
=> PR fix for PR 534

.ci/docker/Dockerfile.rocky88ci, .github/workflows/hirs_unit_tests.yml
closes #570
Need to replace the current unit test yaml file with this one
Need to add the Rocky 8.8 Dockerfile
=> updated github actions unit test yml, added Rocky 8.8 Dockerfile, resolves issue 570

HIRS_Utils/src/test/java/hirs/data/persist/DigestTest.java
Migrates DigestTest and accompanying unit tests to the main branch. Closes #572.
=> [#572] Add DigestTest unit tests

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/RestfulAttestationCertificateAuthority.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateDetailsPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/DevicePageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/HelpPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IndexPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/LombokLoggingController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PolicyPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/RimDatabasePageController.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java, HIRS_AttestationCAPortal/src/main/resources/application.properties, HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/tags/page.tag
This change allows greater control over the URLs that are mapped to Spring requests.
=> Context change to enable path control [no ci]

.ci/docker/Dockerfile.rocky88ci
=> Updated dockerfile for github actions unit test

package/scripts/db/db_create.sh, package/scripts/pki/pki_setup.sh
Checks for an existing aca.properties and uses existing passwords from the file if found.
closes #599
=> Added check for existing aca.properties in the ACA setup files

.github/workflows/hirs_package_linux.yml
Adds an action that creates and archives all HIRS jar files, a  bootable war file, an ACA RPM and ACA DEB package for each push.
Closes #606
=> Creates a build/package action for V3

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java, HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
Updated the Rim Validator to remove direct object parameters from the database and pass in the information the methods needed to function
=> Update to the RIM Validator

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/AbstractEntity.java, HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/EndorsementCredentialRepository.java, HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
These are fixes for issues found via unit test that are in PR #652 .  But that PR is currently still WIP and these changes have nothing to do with why that PR is WIP.  Therefore PR just covers these changes to the creation time not being saved/reset.
=> Creation Date fix

HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/PlatformCredentialsPageControllerTest.java, HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/PolicyPageControllerTest.java, HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/TrustChainManagementPageControllerTest.java
New tests merged:
PlatformCredentialsPageControllerTest
PolicyPageControllerTest
TrustChainManagementPageControllerTest
=> [#655] Added the final 3 Page Controller integration tests

HIRS_AttestationCAPortal/build.gradle, package/scripts/aca/aca_setup.sh
VERSION file is created by the aca_setup script.
=> Added VERSION file to /etc/hirs/aca

HIRS_Utils/config/spotbugs/spotbugs-exclude.xml, HIRS_Utils/src/main/java/hirs/utils/swid/SwidTagConstants.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiGptPartition.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiSpecIdEvent.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java
Initial set of changes for #642 that are fixes for HIRS_Utils. In addition, this and the following pushes will have changes for #651 because spot bugs doesn't like how Lombok handles hashCode and equals
=> [#642] HIRS_Utils spotbugs fixes

HIRS_Provisioner.NET/hirs/Directory.Build.targets, HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
Updates WiX project reference to 3.14.0.
=> V3 Update WiX

HIRS_Provisioner.NET/hirs/Directory.Build.targets, HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
Updates WiX project reference to 3.14.0.
=> V2 Update WiX

HIRS_AttestationCAPortal/build.gradle, build.gradle, package/linux/aca/aca_check_setup.sh, package/linux/aca/aca_remove_setup.sh, package/linux/aca/aca_setup.sh, package/linux/db/db_create.sh, package/linux/db/mysql_util.sh
Added a setup check for exiting setup files.
Fixed a permission issue with mariadb on Rocky 9.
closes #749
=> [#749] ACA setup check

HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
The title describes the main change.  Minor changes include expanding import statements and cleaning up log messages.
Closes #736
=> [#736] Add BC validator for validation

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/PcrValidator.java
This change logs the values of calculatedString and quoteString during firmware validation debug.
=> [#801] Log hash strings for debug purposes

.ci/docker/Dockerfile.aca-windows, .github/workflows/create_aca_images.yml, package/win/aca/aca_common.ps1
These changes allow the v3 aca docker image workflow to work again.
=> Windows Docker images needed some work

.ci/system-tests/container/pc_setup.sh, .ci/system-tests/container/rim_setup.sh, .ci/system-tests/run_system_tests.sh, .ci/system-tests/sys_test_common.sh, .ci/system-tests/tests/aca_policy_tests.sh, .ci/system-tests/tests/platform_cert_tests.sh, .ci/system-tests/tests/rim_system_tests.sh, .github/workflows/system_test.yml
Fixes ci error reporting. Test for failed test is [here](https://github.com/nsacyber/HIRS/actions/runs/10099471763/job/27928718323#step:19:32). Saves log on error.
=> Fixes CI test error checking

NOTICE.md
Updating NOTICE file to include latest dependencies. Closes #827.
=> {#827] Updating NOTICE file

tools/tcg_eventlog_tool/build.gradle
=> Changed tcg_eventlog_tool to use amd64 for debian packaging

HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
Adds Storage support for ATA, SCSI
A few other fixes
=> Provisioner to use updated registry libraries

.github/workflows/dotnet_provisioner_unit_tests.yml
Ubuntu-20.04 --> Ubuntu-latest
Closes #917
=> [#917] Upgrade Ubuntu image in dotnet provisioner workflow

HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/PcrValidator.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TCGEventLog.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TpmPcrEvent.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiHandoffTable.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiGuid.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java, HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java, HIRS_Utils/src/main/resources/vendor-table.json, tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
Closes Issue #990.
Change log levels for events being ignored in [PcrValidator](https://github.com/nsacyber/HIRS/blob/e48e9ddc9e37e33816360efb172d33076ef3679b/HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/PcrValidator.java#L179). 
Added 6 new guids.
=> Changing log levels; adding guids
